http_port 3128

acl allowed_domains dstdomain "/etc/squid/allowed_domains.txt"
http_access allow allowed_domains
http_access deny all

cache deny all
access_log stdio:/dev/stdout
cache_log /dev/stderr
pid_filename none
coredump_dir none

request_header_access Proxy-Authorization deny all
forwarded_for delete
via off
