"use strict";
const HOST="org.fa3.browser.session_bridge",PROTOCOL="fa3.browser-session-bridge.v1",EXTENSION_ID="hkcdjepmkpeglfgejcejjdpdidinipdc",MAX_TTL_SECONDS=600;
const ALLOWED_ACTION_SCOPE=new Set(["observe","click","type","select","scroll","key","human-assistance"]);
const ALLOWED_APPROVAL_AUTHORITIES=new Set(["AUTH-HUMAN","FA3-AUTH-SECURITY-GOV-001"]);
const ALLOWED_KEYS=new Set(["Enter","Tab","Escape","ArrowUp","ArrowDown","ArrowLeft","ArrowRight","Backspace","Delete","Home","End","PageUp","PageDown"]);
let nativePort=null,reconnectTimer=null,session=null,requestSerial=Promise.resolve();
const opaqueTabRef=id=>`tab:${id}`,opaqueWindowRef=id=>`window:${id}`;
function parseOpaque(ref,prefix){if(typeof ref!=="string"||!ref.startsWith(prefix+":"))throw new Error("INVALID_OPAQUE_REF");const v=Number(ref.slice(prefix.length+1));if(!Number.isInteger(v)||v<0)throw new Error("INVALID_OPAQUE_REF");return v}
function safeOrigin(url){try{const p=new URL(url);return p.protocol==="http:"||p.protocol==="https:"?p.origin:`${p.protocol}//`}catch{return"opaque://"}}
const nowMs=()=>Date.now();
function assertSession(id){if(!session||session.sessionId!==id)throw new Error("SESSION_NOT_ACTIVE");return session}
function validateApproval(a){if(!a||a.approved!==true)throw new Error("APPROVAL_REQUIRED");if(!ALLOWED_APPROVAL_AUTHORITIES.has(String(a.authority||"")))throw new Error("APPROVAL_AUTHORITY_INVALID");if(typeof a.receipt!=="string"||a.receipt.length<8||a.receipt.length>512)throw new Error("APPROVAL_RECEIPT_INVALID")}
function normalizeActionScope(v){if(!Array.isArray(v)||!v.length)throw new Error("ACTION_SCOPE_REQUIRED");const u=[...new Set(v.map(String))];if(u.some(x=>!ALLOWED_ACTION_SCOPE.has(x)))throw new Error("ACTION_SCOPE_INVALID");return u.sort()}
function emitEvent(event,payload){if(nativePort)try{nativePort.postMessage({type:"event",event,payload})}catch{}}
function leaseForTab(id){if(!session)return null;const l=session.borrowed.get(id)||null;if(!l)return null;if(l.expiresAtMs<=nowMs()){clearTimeout(l.timer);session.borrowed.delete(id);emitEvent("lease.expired",{session_id:session.sessionId,lease_id:l.leaseId,tab_ref:opaqueTabRef(id)});return null}return l}
async function tabScope(tab){if(!session)return"USER";if(leaseForTab(tab.id))return"BORROWED";return tab.windowId===session.agentWindowId?"AGENT":"USER"}
async function controlledTab(tabRef,requiredAction){if(!session)throw new Error("SESSION_NOT_ACTIVE");const id=parseOpaque(tabRef,"tab"),tab=await chrome.tabs.get(id),lease=leaseForTab(id);if(lease){if(safeOrigin(tab.url||"")!==lease.originScope)throw new Error("ORIGIN_SCOPE_MISMATCH");if(requiredAction&&!lease.actionScope.includes(requiredAction))throw new Error("ACTION_SCOPE_DENIED");return{tab,lease,scope:"BORROWED"}}if(tab.windowId!==session.agentWindowId)throw new Error("TAB_NOT_CONTROLLED");return{tab,lease:null,scope:"AGENT"}}
async function sessionStart(p){if(session)throw new Error("SESSION_ALREADY_ACTIVE");const id=String(p.session_id||"").trim();if(!/^[A-Za-z0-9._:+-]{1,128}$/.test(id))throw new Error("SESSION_ID_INVALID");const w=await chrome.windows.create({url:"about:blank",focused:false,type:"normal"});if(!w||!Number.isInteger(w.id))throw new Error("AGENT_WINDOW_CREATE_FAILED");session={sessionId:id,agentWindowId:w.id,borrowed:new Map(),assistance:new Map()};return{status:"STARTED",session_id:id,agent_window_ref:opaqueWindowRef(w.id),logical_borrow_without_reparenting:true}}
async function assistanceCancel(p){const s=assertSession(String(p.session_id||"")),id=String(p.assistance_request_id||""),r=s.assistance.get(id);if(!r)throw new Error("ASSISTANCE_REQUEST_NOT_ACTIVE");try{await chrome.scripting.executeScript({target:{tabId:r.tabId},func:removeAssistanceOverlay,args:[id]})}catch{}s.assistance.delete(id);emitEvent("assistance.result",{session_id:s.sessionId,assistance_request_id:id,result:"CANCELLED"});return{status:"CANCELLED",assistance_request_id:id,human_completion_claim:false}}
async function sessionStop(p){const s=assertSession(String(p.session_id||""));const aids=[...s.assistance.keys()];for(const id of aids)await assistanceCancel({session_id:s.sessionId,assistance_request_id:id}).catch(()=>{});const leases=[...s.borrowed.values()];for(const l of leases){clearTimeout(l.timer);s.borrowed.delete(l.tabId);emitEvent("lease.returned",{session_id:s.sessionId,lease_id:l.leaseId,tab_ref:opaqueTabRef(l.tabId),reason:"SESSION_STOP"})}const wid=s.agentWindowId;session=null;try{await chrome.windows.remove(wid)}catch{}return{status:"STOPPED",returned_leases:leases.length,cancelled_assistance:aids.length}}
async function tabsList(p){assertSession(String(p.session_id||""));const tabs=await chrome.tabs.query({}),out=[];for(const tab of tabs){if(!Number.isInteger(tab.id)||!Number.isInteger(tab.windowId))continue;out.push({tab_ref:opaqueTabRef(tab.id),window_ref:opaqueWindowRef(tab.windowId),index:Number(tab.index||0),active:tab.active===true,origin:safeOrigin(tab.url||""),scope:await tabScope(tab)})}return{status:"OK",tabs:out}}
async function tabBorrow(p){const s=assertSession(String(p.session_id||""));validateApproval(p.approval);const id=parseOpaque(p.tab_ref,"tab"),tab=await chrome.tabs.get(id);if(tab.windowId===s.agentWindowId)throw new Error("AGENT_TAB_DOES_NOT_REQUIRE_BORROW");if(leaseForTab(id))throw new Error("TAB_ALREADY_BORROWED");const origin=String(p.origin_scope||"");if(!/^https?:\/\//.test(origin)||safeOrigin(tab.url||"")!==origin)throw new Error("ORIGIN_SCOPE_MISMATCH");const scope=normalizeActionScope(p.action_scope),ttl=Number(p.ttl_seconds);if(!Number.isInteger(ttl)||ttl<1||ttl>MAX_TTL_SECONDS)throw new Error("LEASE_TTL_INVALID");const leaseId=`lease-${crypto.randomUUID()}`,issued=nowMs(),l={leaseId,tabId:id,originScope:origin,actionScope:scope,issuedAtMs:issued,expiresAtMs:issued+ttl*1000,originalWindowId:tab.windowId,originalIndex:tab.index,approvalReceipt:p.approval.receipt,timer:null};l.timer=setTimeout(()=>{if(!session||session.sessionId!==s.sessionId)return;const cur=session.borrowed.get(id);if(!cur||cur.leaseId!==leaseId)return;session.borrowed.delete(id);emitEvent("lease.expired",{session_id:s.sessionId,lease_id:leaseId,tab_ref:opaqueTabRef(id)})},ttl*1000);s.borrowed.set(id,l);return{status:"BORROWED",lease_id:leaseId,session_id:s.sessionId,tab_ref:opaqueTabRef(id),origin_scope:origin,action_scope:scope,issued_at_epoch_ms:issued,expires_at_epoch_ms:l.expiresAtMs,original_window_ref:opaqueWindowRef(tab.windowId),original_index:tab.index,logical_borrow_without_reparenting:true}}
async function tabReturn(p){const s=assertSession(String(p.session_id||"")),id=parseOpaque(p.tab_ref,"tab"),l=leaseForTab(id);if(!l)throw new Error("TAB_LEASE_NOT_ACTIVE");if(p.lease_id&&p.lease_id!==l.leaseId)throw new Error("LEASE_ID_MISMATCH");clearTimeout(l.timer);s.borrowed.delete(id);emitEvent("lease.returned",{session_id:s.sessionId,lease_id:l.leaseId,tab_ref:opaqueTabRef(id),reason:"EXPLICIT_RETURN"});return{status:"RETURNED",lease_id:l.leaseId,tab_ref:opaqueTabRef(id),logical_borrow_without_reparenting:true}}
function observePage(){const html=document.documentElement?document.documentElement.outerHTML:"";if(html.length>4000000)return{error:"DOM_TOO_LARGE"};const nodes=Array.from(document.querySelectorAll('a[href],button,input,textarea,select,[role="button"],[contenteditable="true"]'));if(nodes.length>512)return{error:"TOO_MANY_ACTIONABLE_ELEMENTS"};const rows=[];nodes.forEach((el,index)=>{const tag=(el.tagName||"").toLowerCase(),type=(el.getAttribute("type")||"").toLowerCase(),style=getComputedStyle(el),rect=el.getBoundingClientRect(),visible=style.visibility!=="hidden"&&style.display!=="none"&&Number(style.opacity||1)>0&&rect.width>0&&rect.height>0;let occluded=false;if(visible){const x=Math.max(0,Math.min(innerWidth-1,rect.left+rect.width/2)),y=Math.max(0,Math.min(innerHeight-1,rect.top+rect.height/2)),top=document.elementFromPoint(x,y);occluded=!!top&&top!==el&&!el.contains(top)}const enabled=!el.disabled&&el.getAttribute("aria-disabled")!=="true",textControl=tag==="textarea"||el.isContentEditable||(tag==="input"&&!["button","submit","reset","checkbox","radio","file","hidden"].includes(type)),actions=tag==="select"?["SELECT","SCROLL_INTO_VIEW"]:(textControl?["TYPE_TEXT","PRESS_KEY","SCROLL_INTO_VIEW"]:["CLICK","SCROLL_INTO_VIEW"]),rawLabel=el.getAttribute("aria-label")||el.innerText||el.getAttribute("placeholder")||el.getAttribute("name")||"",label=String(rawLabel).replace(/\s+/g," ").trim().slice(0,256);let value=null;if(tag==="select")value=String(el.value||"").slice(0,4096);else if(textControl&&type!=="password")value=String(el.value||"").slice(0,4096);rows.push({element_id:`el-${String(index).padStart(4,"0")}`,role:el.getAttribute("role")||(tag==="a"?"link":tag),label,value,visible,enabled,occluded,supported_actions:actions,metadata:{sensitive:type==="password"}})});let safeUrl="";try{safeUrl=location.origin+location.pathname}catch{safeUrl=location.protocol}return{url:safeUrl,timeOrigin:performance.timeOrigin,html,elements:rows}}
function executePageAction(index,operation,parameters){const nodes=Array.from(document.querySelectorAll('a[href],button,input,textarea,select,[role="button"],[contenteditable="true"]')),el=nodes[index];if(!el||!el.isConnected)return{error:"TARGET_MISSING"};const style=getComputedStyle(el),rect=el.getBoundingClientRect(),visible=style.visibility!=="hidden"&&style.display!=="none"&&Number(style.opacity||1)>0&&rect.width>0&&rect.height>0;if(!visible)return{error:"TARGET_NOT_VISIBLE"};const enabled=!el.disabled&&el.getAttribute("aria-disabled")!=="true";if(["CLICK","TYPE_TEXT","SELECT","PRESS_KEY"].includes(operation)&&!enabled)return{error:"TARGET_DISABLED"};if(operation==="CLICK")el.click();else if(operation==="TYPE_TEXT"){const text=parameters&&typeof parameters.text==="string"?parameters.text:null;if(text===null||text.length>32768)return{error:"PARAMETERS_INVALID"};el.focus();if("value"in el)el.value=text;else el.textContent=text;el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}))}else if(operation==="SELECT"){const value=parameters&&typeof parameters.value==="string"?parameters.value:null;if(value===null||value.length>4096||el.tagName!=="SELECT")return{error:"PARAMETERS_INVALID"};el.value=value;el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}))}else if(operation==="SCROLL_INTO_VIEW")el.scrollIntoView({block:"center",inline:"center"});else if(operation==="PRESS_KEY"){const key=parameters&&typeof parameters.key==="string"?parameters.key:"";el.focus();el.dispatchEvent(new KeyboardEvent("keydown",{key,bubbles:true}));el.dispatchEvent(new KeyboardEvent("keyup",{key,bubbles:true}))}else return{error:"OPERATION_UNSUPPORTED"};return{status:"EXECUTED",operation,target_index:index}}
async function pageObserve(p){const{tab}=await controlledTab(p.tab_ref,"observe"),r=await chrome.scripting.executeScript({target:{tabId:tab.id},func:observePage}),v=r&&r[0]&&r[0].result;if(!v||v.error)throw new Error(v&&v.error?v.error:"OBSERVATION_FAILED");return{status:"OBSERVED",tab_ref:p.tab_ref,observation:v}}
async function pageExecute(p){const op=String(p.operation||""),map={CLICK:"click",TYPE_TEXT:"type",SELECT:"select",SCROLL_INTO_VIEW:"scroll",PRESS_KEY:"key"},need=map[op];if(!need)throw new Error("OPERATION_UNSUPPORTED");const{tab}=await controlledTab(p.tab_ref,need),m=/^el-(\d{4})$/.exec(String(p.target_id||""));if(!m)throw new Error("TARGET_ID_INVALID");if(op==="PRESS_KEY"&&!ALLOWED_KEYS.has(String((p.parameters||{}).key||"")))throw new Error("KEY_NOT_ALLOWED");const r=await chrome.scripting.executeScript({target:{tabId:tab.id},func:executePageAction,args:[Number(m[1]),op,p.parameters||{}]}),v=r&&r[0]&&r[0].result;if(!v||v.error)throw new Error(v&&v.error?v.error:"EXECUTION_FAILED");return{status:"EXECUTED",tab_ref:p.tab_ref,result:v}}
function assistanceOverlay(prompt,id){const old=document.getElementById("fa3-human-assistance-overlay");if(old)old.remove();const root=document.createElement("div");root.id="fa3-human-assistance-overlay";Object.assign(root.style,{position:"fixed",inset:"0",zIndex:"2147483647",background:"rgba(0,0,0,.55)",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"sans-serif"});const card=document.createElement("div");Object.assign(card.style,{maxWidth:"560px",background:"white",color:"black",padding:"24px",borderRadius:"12px",boxShadow:"0 8px 30px rgba(0,0,0,.3)"});const title=document.createElement("strong");title.textContent="FA3 human assistance requested";const p=document.createElement("p");p.textContent=prompt;const row=document.createElement("div");Object.assign(row.style,{display:"flex",gap:"12px"});const done=document.createElement("button");done.textContent="Continue";done.id="fa3-human-assistance-continue";const cancel=document.createElement("button");cancel.textContent="Cancel";cancel.id="fa3-human-assistance-cancel";done.onclick=()=>chrome.runtime.sendMessage({type:"fa3-human-assistance-result",request_id:id,result:"COMPLETED"});cancel.onclick=()=>chrome.runtime.sendMessage({type:"fa3-human-assistance-result",request_id:id,result:"CANCELLED"});row.append(done,cancel);card.append(title,p,row);root.append(card);document.documentElement.append(root);return{visible:true,request_id:id}}
function removeAssistanceOverlay(id){const root=document.getElementById("fa3-human-assistance-overlay");if(root)root.remove();return{removed:true,request_id:id}}
async function assistanceRequest(p){const s=assertSession(String(p.session_id||""));validateApproval(p.approval);const prompt=String(p.prompt||"").trim();if(!prompt||prompt.length>1024)throw new Error("ASSISTANCE_PROMPT_INVALID");const{tab}=await controlledTab(p.tab_ref,"human-assistance"),id=`assist-${crypto.randomUUID()}`,r=await chrome.scripting.executeScript({target:{tabId:tab.id},func:assistanceOverlay,args:[prompt,id]});if(!r||!r[0]||!r[0].result||r[0].result.visible!==true)throw new Error("ASSISTANCE_OVERLAY_FAILED");s.assistance.set(id,{tabId:tab.id,state:"PENDING_HUMAN",createdAtMs:nowMs()});return{status:"PENDING_HUMAN",assistance_request_id:id,tab_ref:p.tab_ref,human_completion_claim:false}}
chrome.runtime.onMessage.addListener((m,sender)=>{if(!m||m.type!=="fa3-human-assistance-result"||!session)return;const id=String(m.request_id||""),r=session.assistance.get(id);if(!r||!sender.tab||sender.tab.id!==r.tabId)return;const result=m.result==="COMPLETED"?"COMPLETED":"CANCELLED";session.assistance.delete(id);emitEvent("assistance.result",{session_id:session.sessionId,assistance_request_id:id,result,tab_ref:opaqueTabRef(r.tabId)})});
async function dispatch(method,p){if(method==="ping")return{status:"PONG",protocol:PROTOCOL,extension_id:chrome.runtime.id};if(method==="session.start")return sessionStart(p);if(method==="session.stop")return sessionStop(p);if(method==="tabs.list")return tabsList(p);if(method==="tab.borrow")return tabBorrow(p);if(method==="tab.return")return tabReturn(p);if(method==="page.observe")return pageObserve(p);if(method==="page.execute")return pageExecute(p);if(method==="assist.request")return assistanceRequest(p);if(method==="assist.cancel")return assistanceCancel(p);throw new Error("METHOD_NOT_ALLOWED")}
function handleRequest(m){if(!m||m.type!=="request"||typeof m.request_id!=="string"||typeof m.method!=="string")return;requestSerial=requestSerial.then(async()=>{try{const result=await dispatch(m.method,m.params||{});nativePort.postMessage({type:"response",reply_to:m.request_id,ok:true,result})}catch(e){nativePort.postMessage({type:"response",reply_to:m.request_id,ok:false,error:{code:String(e&&e.message?e.message:"REQUEST_FAILED")}})}})}
function connectNative(){if(nativePort)return;try{nativePort=chrome.runtime.connectNative(HOST);nativePort.onMessage.addListener(handleRequest);nativePort.onDisconnect.addListener(()=>{nativePort=null;clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connectNative,1000)});nativePort.postMessage({type:"hello",protocol:PROTOCOL,extension_id:chrome.runtime.id,expected_extension_id:EXTENSION_ID,authority:false})}catch{nativePort=null;clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connectNative,1000)}}
connectNative();
