import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick.Window

ApplicationWindow {
    id: window
    width: Math.round(1580 * fa3Settings.uiScale)
    height: Math.round(980 * fa3Settings.uiScale)
    minimumWidth: 1120
    minimumHeight: 700
    visible: true
    title: "Final Architecture 3.0 — Control Center"

    SystemPalette { id: systemPalette }

    property real uiScale: fa3Settings.uiScale
    property real fontScale: fa3Settings.baseFontSize / 13.0
    property bool forcedDark: fa3Settings.themeMode === "dark"
    property bool forcedLight: fa3Settings.themeMode === "light"
    property color surface0: forcedDark ? "#17191d" : forcedLight ? "#f3f5f7" : systemPalette.window
    property color surface1: forcedDark ? "#202329" : forcedLight ? "#ffffff" : systemPalette.base
    property color surface2: forcedDark ? "#2a2e35" : forcedLight ? "#e9edf2" : systemPalette.alternateBase
    property color textPrimary: forcedDark ? "#f2f4f7" : forcedLight ? "#1b1e23" : systemPalette.windowText
    property color textMuted: Qt.rgba(textPrimary.r, textPrimary.g, textPrimary.b, 0.62)
    property color accent: systemPalette.highlight
    property int selectedIndex: 0

    color: surface0
    palette.window: surface0
    palette.base: surface1
    palette.alternateBase: surface2
    palette.windowText: textPrimary
    palette.text: textPrimary
    palette.button: surface2
    palette.buttonText: textPrimary
    palette.highlight: accent
    palette.highlightedText: systemPalette.highlightedText

    function t(hu, en) { return fa3Settings.language === "en" ? en : hu }
    function px(value) { return Math.max(9, Math.round(value * fontScale)) }
    function navLabel(key) {
        const labels = {
            command: ["Command Center", "Command Center"], projects: ["Projektek", "Projects"], studio: ["AI Studio", "AI Studio"], mentor: ["AI Mentor", "AI Mentor"], coach: ["AI Coach", "AI Coach"], agents: ["Agentek & Workflow-k", "Agents & Workflows"], models: ["Modellek & Providerek", "Models & Providers"], architecture: ["Architektúra", "Architecture"], resources: ["Erőforrások", "Resources"], security: ["Biztonság & Jóváhagyás", "Security & Approvals"], observability: ["Observability", "Observability"], evidence: ["Evidence", "Evidence"], integrations: ["Integrációk", "Integrations"], system: ["Rendszer", "System"], settings: ["Beállítások", "Settings"]
        }
        return fa3Settings.language === "en" ? labels[key][1] : labels[key][0]
    }

    property var navigationModel: [
        { key: "command", iconText: "⌂" }, { key: "projects", iconText: "▣" }, { key: "studio", iconText: "✦" }, { key: "mentor", iconText: "M" }, { key: "coach", iconText: "C" }, { key: "agents", iconText: "⌘" }, { key: "models", iconText: "◫" }, { key: "architecture", iconText: "◇" }, { key: "resources", iconText: "▤" }, { key: "security", iconText: "◆" }, { key: "observability", iconText: "⌁" }, { key: "evidence", iconText: "✓" }, { key: "integrations", iconText: "↔" }, { key: "system", iconText: "⚙" }, { key: "settings", iconText: "☰" }
    ]

    component Panel: Rectangle { radius: Math.round(12 * window.uiScale); color: window.surface1; border.color: Qt.rgba(window.textPrimary.r, window.textPrimary.g, window.textPrimary.b, 0.10) }
    component SectionTitle: Column { property string title: ""; property string subtitle: ""; spacing: 4; Label { text: parent.title; font.pixelSize: window.px(24); font.bold: true }; Label { text: parent.subtitle; color: window.textMuted; font.pixelSize: window.px(13); wrapMode: Text.WordWrap; width: parent.width } }
    component MetricCard: Panel { property string label: ""; property string value: ""; property string note: ""; implicitWidth: Math.round(195 * window.uiScale); implicitHeight: Math.round(112 * window.uiScale); Column { anchors.fill: parent; anchors.margins: Math.round(16 * window.uiScale); spacing: 6; Label { text: parent.parent.label; color: window.textMuted; font.pixelSize: window.px(12) }; Label { text: parent.parent.value; font.pixelSize: window.px(27); font.bold: true }; Label { text: parent.parent.note; color: window.textMuted; font.pixelSize: window.px(11); elide: Text.ElideRight; width: parent.width } } }
    component ModuleCard: Panel { property string title: ""; property string subtitle: ""; property string badge: "READY"; implicitWidth: Math.round(255 * window.uiScale); implicitHeight: Math.round(124 * window.uiScale); Column { anchors.fill: parent; anchors.margins: Math.round(16 * window.uiScale); spacing: 8; RowLayout { width: parent.width; Label { text: parent.parent.parent.title; font.pixelSize: window.px(16); font.bold: true; Layout.fillWidth: true }; Label { text: parent.parent.parent.badge; color: window.accent; font.pixelSize: window.px(10); font.bold: true } }; Label { text: parent.parent.subtitle; color: window.textMuted; wrapMode: Text.WordWrap; width: parent.width; font.pixelSize: window.px(12) } } }

    header: ToolBar {
        height: Math.round(64 * window.uiScale)
        RowLayout {
            anchors.fill: parent; anchors.leftMargin: 18; anchors.rightMargin: 18; spacing: 12
            Label { text: "FA3"; font.pixelSize: window.px(21); font.bold: true }
            Rectangle { width: 1; height: 28; color: Qt.rgba(window.textPrimary.r, window.textPrimary.g, window.textPrimary.b, 0.16) }
            Label { text: "Final Architecture 3.0"; font.pixelSize: window.px(15); font.bold: true }
            Item { Layout.fillWidth: true }
            Button { text: window.t("Kérdezd a Mentort", "Ask Mentor"); enabled: fa3Settings.value("mentor/enabled", true); onClicked: window.selectedIndex = 3 }
            Button { text: window.t("Kérdezd a Coachot", "Ask Coach"); enabled: fa3Settings.value("coach/enabled", true); onClicked: window.selectedIndex = 4 }
            Label { text: "CANONICAL"; color: window.accent; font.bold: true; font.pixelSize: window.px(10) }
            Label { text: "143 capabilities"; color: window.textMuted; font.pixelSize: window.px(11) }
            ToolButton { text: "↻"; ToolTip.visible: hovered; ToolTip.text: window.t("Canonical állapot frissítése", "Refresh canonical state"); onClicked: fa3Repository.refresh() }
        }
    }

    RowLayout {
        anchors.fill: parent; spacing: 0
        Rectangle {
            Layout.preferredWidth: Math.round(260 * window.uiScale); Layout.fillHeight: true; color: window.surface1; border.color: Qt.rgba(window.textPrimary.r, window.textPrimary.g, window.textPrimary.b, 0.08)
            ColumnLayout {
                anchors.fill: parent; anchors.margins: 10; spacing: 8
                ListView { Layout.fillWidth: true; Layout.fillHeight: true; clip: true; model: window.navigationModel; currentIndex: window.selectedIndex; delegate: ItemDelegate { width: ListView.view.width; height: Math.round(44 * window.uiScale); highlighted: index === window.selectedIndex; onClicked: window.selectedIndex = index; contentItem: Row { spacing: 12; Label { text: modelData.iconText; width: 24; horizontalAlignment: Text.AlignHCenter; font.pixelSize: window.px(12) }; Label { text: window.navLabel(modelData.key); font.pixelSize: window.px(12) } } } }
                Panel { Layout.fillWidth: true; Layout.preferredHeight: Math.round(116 * window.uiScale); Column { anchors.fill: parent; anchors.margins: 12; spacing: 5; Label { text: "Repository"; font.bold: true; font.pixelSize: window.px(11) }; Label { width: parent.width; text: fa3Repository.repoRoot; color: window.textMuted; elide: Text.ElideMiddle; font.pixelSize: window.px(9) }; Label { text: window.t("Frissítve: ", "Updated: ") + fa3Repository.lastRefresh; color: window.textMuted; font.pixelSize: window.px(9) } } }
            }
        }

        StackLayout {
            Layout.fillWidth: true; Layout.fillHeight: true; currentIndex: window.selectedIndex
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Command Center"; subtitle: window.t("FA3 rendszerállapot, canonical integritás és operátori fókusz", "FA3 state, canonical integrity and operator focus") }; Flow { Layout.fillWidth: true; spacing: 12; MetricCard { label: window.t("Canonical rekord", "Canonical records"); value: fa3Repository.canonicalRecordCount.toString(); note: "read-only projection" }; MetricCard { label: "Profile"; value: fa3Repository.profileCount.toString(); note: "canonical profiles" }; MetricCard { label: "Provider"; value: fa3Repository.providerCount.toString(); note: "registered providers" }; MetricCard { label: "Evidence"; value: fa3Repository.evidenceCount.toString(); note: "evidence records" }; MetricCard { label: "Pending"; value: fa3Repository.pendingCount.toString(); note: "requires attention" } }; Flow { Layout.fillWidth: true; spacing: 12; ModuleCard { title: "AI Mentor"; subtitle: window.t("Tanítás, magyarázat, mastery és Practice Lab projection", "Teaching, explanation, mastery and Practice Lab projection"); badge: fa3Settings.value("mentor/enabled", true) ? "ENABLED" : "OFF" }; ModuleCard { title: "AI Coach"; subtitle: window.t("Célok, következő lépések, blockerek és progress coaching", "Goals, next actions, blockers and progress coaching"); badge: fa3Settings.value("coach/enabled", true) ? "ENABLED" : "OFF" }; ModuleCard { title: window.t("GUI profil", "GUI profile"); subtitle: fa3Settings.value("dashboard/profile", "Studio"); badge: fa3Settings.themeMode.toUpperCase() } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Projects & Workspaces"; subtitle: window.t("Projektek, assetek és knowledge-context egy közös operátori nézetben", "Projects, assets and knowledge context in one operator view") }; Flow { Layout.fillWidth: true; spacing: 12; ModuleCard { title: "Active Workspace"; subtitle: fa3Settings.value("paths/workspaces", "~/FA3-Workspaces"); badge: "LOCAL" }; ModuleCard { title: "Projects"; subtitle: fa3Settings.value("paths/projects", "~/FA3-Projects"); badge: "PATH" }; ModuleCard { title: "Knowledge"; subtitle: "Canonical RAG/read projection"; badge: "READ" } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "AI Studio"; subtitle: window.t("A lokális kreatív pipeline egységes felülete", "Unified surface for the local creative pipeline") }; Flow { Layout.fillWidth: true; spacing: 12; ModuleCard { title: "Image"; subtitle: "ComfyUI / InvokeAI / editor bridge" }; ModuleCard { title: "Video"; subtitle: "Generation, Kdenlive, editorial, compositing" }; ModuleCard { title: "Animation"; subtitle: "Motion, character and timeline workflows" }; ModuleCard { title: "3D / VFX"; subtitle: "Geometry, Bforartists/Blender, Natron/Gaffer" }; ModuleCard { title: "Audio"; subtitle: "STT, TTS, restoration, separation, Voice Fabric" }; ModuleCard { title: "Music"; subtitle: "Generation, stems, DAW, mastering" }; ModuleCard { title: "Story / Screenplay"; subtitle: "FA3 Story production context" } }; Panel { Layout.fillWidth: true; Layout.preferredHeight: 130; Label { anchors.fill: parent; anchors.margins: 18; wrapMode: Text.WordWrap; color: window.textMuted; text: window.t("Az AI Studio execution továbbra is a meglévő model-router, MCP/capability gateway, workflow és Host Resource Broker authority-kon keresztül történik.", "AI Studio execution remains mediated by existing authorities.") } } } }
            MentorPage { settings: fa3Settings; repository: fa3Repository; surface1: window.surface1; surface2: window.surface2; textPrimary: window.textPrimary; textMuted: window.textMuted; accent: window.accent; uiScale: window.uiScale; fontScale: window.fontScale; language: fa3Settings.language }
            CoachPage { settings: fa3Settings; repository: fa3Repository; surface1: window.surface1; surface2: window.surface2; textPrimary: window.textPrimary; textMuted: window.textMuted; accent: window.accent; uiScale: window.uiScale; fontScale: window.fontScale; language: fa3Settings.language }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Agents & Workflows"; subtitle: window.t("Agentek, durable workflow-k és gated tool execution", "Agents, durable workflows and gated tool execution") }; Flow { Layout.fillWidth: true; spacing: 12; ModuleCard { title: "Interactive Agents"; subtitle: "Goose / desktop agent projection"; badge: "ROUTED" }; ModuleCard { title: "Durable Workflows"; subtitle: "Temporal authority projection"; badge: "READ" }; ModuleCard { title: "Tool Execution"; subtitle: "Central MCP mediation"; badge: "GATED" } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Models & Providers"; subtitle: window.t("Model registry, provider projection és inference állapot", "Model registry, provider projection and inference state") }; Flow { Layout.fillWidth: true; spacing: 12; MetricCard { label: "Providers"; value: fa3Repository.providerCount.toString(); note: "canonical provider registry" }; MetricCard { label: "Capabilities"; value: "143"; note: "baseline unchanged" } }; Panel { Layout.fillWidth: true; Layout.preferredHeight: 470; ColumnLayout { anchors.fill: parent; anchors.margins: 14; TextField { id: providerSearch; Layout.fillWidth: true; placeholderText: window.t("Provider keresése…", "Search provider…") }; ListView { Layout.fillWidth: true; Layout.fillHeight: true; clip: true; model: fa3Repository.recordsByCategory("provider").filter(function(v) { return providerSearch.text.length === 0 || v.id.toLowerCase().indexOf(providerSearch.text.toLowerCase()) >= 0 || v.title.toLowerCase().indexOf(providerSearch.text.toLowerCase()) >= 0 }); delegate: ItemDelegate { width: ListView.view.width; height: 48; contentItem: RowLayout { Label { text: modelData.id; font.family: "monospace"; Layout.preferredWidth: 330; elide: Text.ElideRight }; Label { text: modelData.title; Layout.fillWidth: true; elide: Text.ElideRight }; Label { text: modelData.status; color: window.textMuted; Layout.preferredWidth: 170 } } } } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 16; anchors.margins: 24; SectionTitle { title: "Architecture Explorer"; subtitle: window.t("Profiles, contracts, providers, decisions, gates és conformance rekordok", "Profiles, contracts, providers, decisions, gates and conformance records") }; TextField { id: architectureSearch; Layout.fillWidth: true; placeholderText: window.t("Keresés ID, név, státusz vagy path alapján…", "Search by ID, name, status or path…") }; Panel { Layout.fillWidth: true; Layout.preferredHeight: 560; ListView { anchors.fill: parent; anchors.margins: 8; clip: true; model: fa3Repository.searchRecords(architectureSearch.text); delegate: ItemDelegate { width: ListView.view.width; height: 56; onDoubleClicked: fa3Repository.openLocalPath(modelData.path); contentItem: RowLayout { spacing: 10; Label { text: modelData.category.toUpperCase(); color: window.accent; font.pixelSize: window.px(10); Layout.preferredWidth: 84 }; ColumnLayout { Layout.fillWidth: true; spacing: 1; Label { text: modelData.id; font.family: "monospace"; font.bold: true; elide: Text.ElideRight; Layout.fillWidth: true }; Label { text: modelData.title; color: window.textMuted; elide: Text.ElideRight; Layout.fillWidth: true } }; Label { text: modelData.status; color: window.textMuted; Layout.preferredWidth: 180 } } } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Resources"; subtitle: window.t("Read-only host telemetry és ChangeSet-alapú intent", "Read-only host telemetry and ChangeSet-based intent") }; Flow { Layout.fillWidth: true; spacing: 12; MetricCard { label: "Host"; value: fa3Repository.hostName; note: "local host" }; MetricCard { label: "Kernel"; value: fa3Repository.kernelVersion; note: "running kernel" }; MetricCard { label: "CPU threads"; value: fa3Repository.cpuThreads.toString(); note: "read-only discovery" }; MetricCard { label: "Memory"; value: fa3Repository.memoryGiB.toFixed(1) + " GiB"; note: "physical memory" } }; Button { text: window.t("Új typed ChangeSet draft", "New typed ChangeSet draft"); onClicked: changeSetDialog.open() }; Label { id: draftResult; color: window.accent; Layout.fillWidth: true; elide: Text.ElideMiddle } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Security & Approvals"; subtitle: window.t("Policy, approval és security evidence projection", "Policy, approval and security evidence projection") }; Flow { Layout.fillWidth: true; spacing: 12; ModuleCard { title: "Policies"; subtitle: "Effective policy state"; badge: "READ" }; ModuleCard { title: "Approvals"; subtitle: "Pending ChangeSet and execution approvals"; badge: "GATED" }; ModuleCard { title: "Secrets"; subtitle: "Metadata/projection only; no secret values"; badge: "NO VALUES" } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Observability"; subtitle: window.t("Metrics, traces, provenance és rendszerállapot", "Metrics, traces, provenance and system state") }; Flow { Layout.fillWidth: true; spacing: 12; ModuleCard { title: "Metrics"; subtitle: "Resource and service telemetry"; badge: "READ" }; ModuleCard { title: "Traces"; subtitle: "Workflow/tool/model execution trace"; badge: "READ" }; ModuleCard { title: "Provenance"; subtitle: "Artifact and execution provenance"; badge: "READ" } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Evidence"; subtitle: window.t("Conformance, receipts és promotion bizonyítékok", "Conformance, receipts and promotion evidence") }; Flow { Layout.fillWidth: true; spacing: 12; MetricCard { label: "Evidence"; value: fa3Repository.evidenceCount.toString(); note: "repository evidence" }; MetricCard { label: "Pending"; value: fa3Repository.pendingCount.toString(); note: "attention required" } }; Panel { Layout.fillWidth: true; Layout.preferredHeight: 130; Label { anchors.fill: parent; anchors.margins: 18; wrapMode: Text.WordWrap; color: window.textMuted; text: window.t("A GUI evidence rekordokat megjelenít, de nem minősíthet saját magától PASS-nak és nem promotálhat runtime-ot.", "The GUI displays evidence records but cannot self-declare PASS or promote runtime state.") } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "Integrations"; subtitle: window.t("Desktop, DCC, editor, MCP és provider kapcsolatok", "Desktop, DCC, editor, MCP and provider connections") }; Flow { Layout.fillWidth: true; spacing: 12; ModuleCard { title: "Image"; subtitle: fa3Settings.value("integrations/imageEditor", "Krita"); badge: "DEFAULT" }; ModuleCard { title: "Video"; subtitle: fa3Settings.value("integrations/videoEditor", "Kdenlive"); badge: "DEFAULT" }; ModuleCard { title: "Audio"; subtitle: fa3Settings.value("integrations/audioEditor", "Ardour"); badge: "DEFAULT" }; ModuleCard { title: "3D"; subtitle: fa3Settings.value("integrations/threeDEditor", "Bforartists"); badge: "DEFAULT" } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; spacing: 18; anchors.margins: 24; SectionTitle { title: "System"; subtitle: window.t("GUI runtime, repository és platform információ", "GUI runtime, repository and platform information") }; Panel { Layout.fillWidth: true; Layout.preferredHeight: 300; GridLayout { anchors.fill: parent; anchors.margins: 18; columns: 2; columnSpacing: 22; rowSpacing: 10; Label { text: "Application"; color: window.textMuted }; Label { text: "FA3 Control Center 0.2.0" }; Label { text: "Toolkit"; color: window.textMuted }; Label { text: "Qt 6 / QML" }; Label { text: "Repository"; color: window.textMuted }; Label { text: fa3Repository.repoRoot; elide: Text.ElideMiddle; Layout.fillWidth: true }; Label { text: "Config"; color: window.textMuted }; Label { text: fa3Settings.configFilePath; elide: Text.ElideMiddle; Layout.fillWidth: true }; Label { text: "Mutation policy"; color: window.textMuted }; Label { text: "Draft ChangeSet only — no direct privileged execution" }; Label { text: "Display target"; color: window.textMuted }; Label { text: "KDE Plasma / Wayland" } } } } }
            SettingsPage { settings: fa3Settings; surface1: window.surface1; surface2: window.surface2; textPrimary: window.textPrimary; textMuted: window.textMuted; accent: window.accent; uiScale: window.uiScale; fontScale: window.fontScale; language: fa3Settings.language }
        }
    }

    Dialog {
        id: changeSetDialog; title: "Typed ChangeSet draft"; modal: true; anchors.centerIn: parent; width: 580; standardButtons: Dialog.Save | Dialog.Cancel
        ColumnLayout { width: parent.width; spacing: 10; TextField { id: csScope; Layout.fillWidth: true; placeholderText: "Scope" }; TextField { id: csAction; Layout.fillWidth: true; placeholderText: "Action" }; TextField { id: csTarget; Layout.fillWidth: true; placeholderText: "Target" }; TextArea { id: csRationale; Layout.fillWidth: true; Layout.preferredHeight: 120; placeholderText: window.t("Indoklás", "Rationale"); wrapMode: TextEdit.Wrap }; Label { Layout.fillWidth: true; color: window.textMuted; wrapMode: Text.WordWrap; text: "Save → local DRAFT_NOT_SUBMITTED JSON only; no command execution or canonical mutation." } }
        onAccepted: { draftResult.text = fa3Repository.createDraftChangeSet(csScope.text, csAction.text, csTarget.text, csRationale.text); csScope.clear(); csAction.clear(); csTarget.clear(); csRationale.clear() }
    }
}
