import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Item {
    id: root
    required property var settings
    required property color surface1
    required property color surface2
    required property color textPrimary
    required property color textMuted
    required property color accent
    required property real uiScale
    required property real fontScale
    required property string language
    function t(hu, en) { return language === "en" ? en : hu }
    function px(v) { return Math.max(9, Math.round(v * fontScale)) }
    property int sectionIndex: 0
    property var sections: [["appearance", t("Megjelenés", "Appearance")],["locale", t("Nyelv & régió", "Language & Region")],["paths", t("Könyvtárak", "Paths & Libraries")],["workspace", "Workspace"],["dashboard", "Dashboard"],["notifications", t("Értesítések", "Notifications")],["integrations", t("Integrációk", "Integrations")],["mentor", "AI Mentor"],["coach", "AI Coach"],["advanced", t("Haladó", "Advanced")]]

    component Card: Rectangle { radius: 12 * root.uiScale; color: root.surface1; border.color: Qt.rgba(root.textPrimary.r, root.textPrimary.g, root.textPrimary.b, 0.10) }
    component Title: Column { property string title: ""; property string subtitle: ""; spacing: 4; Label { text: parent.title; font.pixelSize: root.px(24); font.bold: true }; Label { text: parent.subtitle; color: root.textMuted; font.pixelSize: root.px(13); wrapMode: Text.WordWrap; width: parent.width } }
    component PathEditor: Card {
        property string settingKey: ""; property string label: ""; implicitHeight: 112 * root.uiScale; property var status: root.settings.pathStatus(pathField.text)
        RowLayout { anchors.fill: parent; anchors.margins: 14; spacing: 10
            ColumnLayout { Layout.preferredWidth: 180 * root.uiScale; Label { text: parent.parent.parent.label; font.bold: true }; Label { text: parent.parent.parent.status.exists ? ((parent.parent.parent.status.writable ? root.t("írható", "writable") : root.t("csak olvasható", "read-only")) + " · " + (parent.parent.parent.status.filesystem || "fs") + " · " + Number(parent.parent.parent.status.freeGiB).toFixed(1) + " GiB free") : root.t("nem létezik / nincs felcsatolva", "missing / not mounted"); color: parent.parent.parent.status.exists ? root.textMuted : "#d99b32"; font.pixelSize: root.px(10) } }
            TextField { id: pathField; Layout.fillWidth: true; text: root.settings.value(parent.parent.parent.settingKey, ""); onEditingFinished: root.settings.setValue(parent.parent.parent.settingKey, text) }
            Button { text: root.t("Tallózás", "Browse"); onClicked: { const chosen = root.settings.chooseDirectory(parent.parent.parent.label, pathField.text); if (chosen.length > 0) { pathField.text = chosen; root.settings.setValue(parent.parent.parent.settingKey, chosen) } } }
        }
    }

    RowLayout {
        anchors.fill: parent; spacing: 0
        Rectangle { Layout.preferredWidth: 230 * root.uiScale; Layout.fillHeight: true; color: root.surface1; border.color: Qt.rgba(root.textPrimary.r, root.textPrimary.g, root.textPrimary.b, 0.08)
            ColumnLayout { anchors.fill: parent; anchors.margins: 12; spacing: 8; Label { text: root.t("Beállítások", "Settings"); font.pixelSize: root.px(18); font.bold: true; Layout.bottomMargin: 8 }; ListView { Layout.fillWidth: true; Layout.fillHeight: true; model: root.sections; delegate: ItemDelegate { width: ListView.view.width; height: 42 * root.uiScale; highlighted: index === root.sectionIndex; text: modelData[1]; onClicked: root.sectionIndex = index } }; Label { Layout.fillWidth: true; wrapMode: Text.WordWrap; text: root.settings.configFilePath; color: root.textMuted; font.pixelSize: root.px(9) } }
        }
        StackLayout {
            Layout.fillWidth: true; Layout.fillHeight: true; currentIndex: root.sectionIndex
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: root.t("Megjelenés", "Appearance"); subtitle: root.t("A Control Center méretezése, betűi és vizuális sűrűsége.", "Control Center scaling, typography and visual density.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 300 * root.uiScale; GridLayout { anchors.fill: parent; anchors.margins: 18; columns: 2; columnSpacing: 24; rowSpacing: 12; Label { text: root.t("UI méretezés", "UI scale") }; RowLayout { Slider { id: scaleSlider; from: 0.8; to: 2.0; stepSize: 0.05; value: root.settings.uiScale; Layout.preferredWidth: 260; onMoved: root.settings.uiScale = value }; Label { text: Math.round(scaleSlider.value * 100) + "%"; Layout.preferredWidth: 60 } }; Label { text: root.t("Alap betűméret", "Base font size") }; SpinBox { from: 10; to: 28; value: root.settings.baseFontSize; editable: true; onValueModified: root.settings.baseFontSize = value }; Label { text: root.t("Téma", "Theme") }; ComboBox { model: ["system", "light", "dark"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.themeMode)); onActivated: root.settings.themeMode = currentText }; Label { text: root.t("Sűrűség", "Density") }; ComboBox { model: ["compact", "normal", "spacious"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.value("appearance/density", "normal"))); onActivated: root.settings.setValue("appearance/density", currentText) }; Label { text: root.t("Kisebb animáció", "Reduced motion") }; Switch { checked: root.settings.value("appearance/reducedMotion", false); onToggled: root.settings.setValue("appearance/reducedMotion", checked) }; Label { text: root.t("Magas kontraszt", "High contrast") }; Switch { checked: root.settings.value("appearance/highContrast", false); onToggled: root.settings.setValue("appearance/highContrast", checked) } } }; Card { Layout.fillWidth: true; Layout.preferredHeight: 130 * root.uiScale; Column { anchors.fill: parent; anchors.margins: 16; spacing: 8; Label { text: root.t("Élő előnézet", "Live preview"); font.bold: true; font.pixelSize: root.px(16) }; Label { text: root.t("A betűméret, UI-scale és téma azonnal alkalmazódik erre az ablakra.", "Font size, UI scale and theme are applied immediately."); color: root.textMuted }; ProgressBar { width: parent.width; value: 0.68 } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: root.t("Nyelv & régió", "Language & Region"); subtitle: root.t("A GUI nyelve különválik a canonical technikai azonosítóktól.", "UI language remains separate from canonical technical identifiers.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 220 * root.uiScale; GridLayout { anchors.fill: parent; anchors.margins: 18; columns: 2; columnSpacing: 24; rowSpacing: 12; Label { text: root.t("GUI nyelve", "UI language") }; ComboBox { model: ["Magyar", "English"]; currentIndex: root.settings.language === "en" ? 1 : 0; onActivated: root.settings.language = currentIndex === 1 ? "en" : "hu" }; Label { text: root.t("Technikai kifejezések angolul", "Keep technical terms in English") }; Switch { checked: root.settings.value("locale/technicalTermsEnglish", true); onToggled: root.settings.setValue("locale/technicalTermsEnglish", checked) }; Label { text: root.t("Megjegyzés", "Note") }; Label { Layout.fillWidth: true; wrapMode: Text.WordWrap; color: root.textMuted; text: "FA3 IDs, ChangeSet, Evidence, Provider, Gate and canonical identifiers are never translated." } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 12; Title { title: root.t("Könyvtárak", "Paths & Libraries"); subtitle: root.t("Felhasználói path role-ok. Ez a felület nem módosít fstab-ot vagy mount policy-t.", "User path roles. This surface never edits fstab or mount policy.") }; PathEditor { Layout.fillWidth: true; label: "Projects"; settingKey: "paths/projects" }; PathEditor { Layout.fillWidth: true; label: "Workspaces"; settingKey: "paths/workspaces" }; PathEditor { Layout.fillWidth: true; label: "Models"; settingKey: "paths/models" }; PathEditor { Layout.fillWidth: true; label: "Model Cache"; settingKey: "paths/modelCache" }; PathEditor { Layout.fillWidth: true; label: "Datasets"; settingKey: "paths/datasets" }; PathEditor { Layout.fillWidth: true; label: "Outputs"; settingKey: "paths/outputs" }; PathEditor { Layout.fillWidth: true; label: "Evidence Export"; settingKey: "paths/evidenceExport" }; PathEditor { Layout.fillWidth: true; label: "Image Assets"; settingKey: "paths/imageAssets" }; PathEditor { Layout.fillWidth: true; label: "Video Assets"; settingKey: "paths/videoAssets" }; PathEditor { Layout.fillWidth: true; label: "Audio Assets"; settingKey: "paths/audioAssets" }; PathEditor { Layout.fillWidth: true; label: "3D Assets"; settingKey: "paths/threeDAssets" }; PathEditor { Layout.fillWidth: true; label: "LUT Library"; settingKey: "paths/lutLibrary" } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: "Workspace"; subtitle: root.t("Indulás, session restore és autosave viselkedés.", "Startup, session restore and autosave behavior.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 230 * root.uiScale; GridLayout { anchors.fill: parent; anchors.margins: 18; columns: 2; rowSpacing: 12; columnSpacing: 24; Label { text: root.t("Induló oldal", "Start page") }; ComboBox { model: ["Command Center", "Projects", "AI Studio", "AI Mentor", "AI Coach", "Evidence"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.value("workspace/startPage", "Command Center"))); onActivated: root.settings.setValue("workspace/startPage", currentText) }; Label { text: root.t("Session visszaállítása", "Restore session") }; Switch { checked: root.settings.value("workspace/restoreSession", true); onToggled: root.settings.setValue("workspace/restoreSession", checked) }; Label { text: root.t("Autosave perc", "Autosave minutes") }; SpinBox { from: 1; to: 60; value: root.settings.value("workspace/autosaveMinutes", 5); onValueModified: root.settings.setValue("workspace/autosaveMinutes", value) } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: "Dashboard"; subtitle: root.t("Operátori nézetprofil és dashboard prioritás.", "Operator view profile and dashboard priority.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 210 * root.uiScale; GridLayout { anchors.fill: parent; anchors.margins: 18; columns: 2; rowSpacing: 12; columnSpacing: 24; Label { text: root.t("Profil", "Profile") }; ComboBox { model: ["Studio", "Operations", "Development", "Presentation", "Custom"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.value("dashboard/profile", "Studio"))); onActivated: root.settings.setValue("dashboard/profile", currentText) }; Label { text: "Telemetry refresh" }; SpinBox { from: 1; to: 60; value: root.settings.value("performance/telemetryRefreshSeconds", 5); onValueModified: root.settings.setValue("performance/telemetryRefreshSeconds", value) } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: root.t("Értesítések", "Notifications"); subtitle: root.t("A GUI saját értesítési preferenciái.", "Notification preferences owned by the GUI.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 190 * root.uiScale; ColumnLayout { anchors.fill: parent; anchors.margins: 18; CheckBox { text: root.t("Desktop értesítések", "Desktop notifications"); checked: root.settings.value("notifications/enabled", true); onToggled: root.settings.setValue("notifications/enabled", checked) }; CheckBox { text: root.t("Csak hiba és kritikus esemény", "Errors and critical events only"); checked: root.settings.value("notifications/errorsOnly", false); onToggled: root.settings.setValue("notifications/errorsOnly", checked) }; Label { text: root.t("Mentor és Coach saját intervenciós/quiet-hours szabályt is használ.", "Mentor and Coach also use their own intervention and quiet-hours rules."); color: root.textMuted; wrapMode: Text.WordWrap; Layout.fillWidth: true } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: root.t("Integrációk", "Integrations"); subtitle: root.t("Alapértelmezett desktop alkalmazások asset-típusonként.", "Default desktop applications by asset type.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 280 * root.uiScale; GridLayout { anchors.fill: parent; anchors.margins: 18; columns: 2; rowSpacing: 12; columnSpacing: 24; Label { text: "Image" }; TextField { text: root.settings.value("integrations/imageEditor", "Krita"); onEditingFinished: root.settings.setValue("integrations/imageEditor", text); Layout.fillWidth: true }; Label { text: "Video" }; TextField { text: root.settings.value("integrations/videoEditor", "Kdenlive"); onEditingFinished: root.settings.setValue("integrations/videoEditor", text); Layout.fillWidth: true }; Label { text: "Audio" }; TextField { text: root.settings.value("integrations/audioEditor", "Ardour"); onEditingFinished: root.settings.setValue("integrations/audioEditor", text); Layout.fillWidth: true }; Label { text: "3D" }; TextField { text: root.settings.value("integrations/threeDEditor", "Bforartists"); onEditingFinished: root.settings.setValue("integrations/threeDEditor", text); Layout.fillWidth: true } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: "AI Mentor"; subtitle: root.t("A Mentor felhasználói preferenciái; ezek nem authority-k.", "Mentor user preferences; these are not authorities.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 330 * root.uiScale; GridLayout { anchors.fill: parent; anchors.margins: 18; columns: 2; rowSpacing: 12; columnSpacing: 24; Label { text: root.t("Engedélyezve", "Enabled") }; Switch { checked: root.settings.value("mentor/enabled", true); onToggled: root.settings.setValue("mentor/enabled", checked) }; Label { text: root.t("Profil", "Profile") }; ComboBox { model: ["Teacher", "Coach-style Tutor", "Expert Assistant", "Study", "Custom"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.value("mentor/profile", "Expert Assistant"))); onActivated: root.settings.setValue("mentor/profile", currentText) }; Label { text: root.t("Kezdeményezés", "Initiative") }; ComboBox { model: ["Silent", "Conservative", "Balanced", "Proactive"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.value("mentor/initiative", "Balanced"))); onActivated: root.settings.setValue("mentor/initiative", currentText) }; Label { text: "Memory policy" }; ComboBox { model: ["Ask every time", "Ask for new categories", "Allow approved categories", "Never write memory"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.value("mentor/memoryPolicy", "Ask for new categories"))); onActivated: root.settings.setValue("mentor/memoryPolicy", currentText) }; Label { text: "Mastery tracking" }; Switch { checked: root.settings.value("mentor/masteryTracking", true); onToggled: root.settings.setValue("mentor/masteryTracking", checked) }; Label { text: "Practice Lab" }; Switch { checked: root.settings.value("mentor/practiceLab", true); onToggled: root.settings.setValue("mentor/practiceLab", checked) } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: "AI Coach"; subtitle: root.t("A Coach külön szerep: cél- és végrehajtási támogatás, nem Mentor profil.", "Coach is a separate role: goal and execution guidance, not a Mentor profile.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 350 * root.uiScale; GridLayout { anchors.fill: parent; anchors.margins: 18; columns: 2; rowSpacing: 12; columnSpacing: 24; Label { text: root.t("Engedélyezve", "Enabled") }; Switch { checked: root.settings.value("coach/enabled", true); onToggled: root.settings.setValue("coach/enabled", checked) }; Label { text: root.t("Profil", "Profile") }; ComboBox { model: ["Supportive", "Structured", "Performance", "Critical Reviewer", "Executive", "Custom"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.value("coach/profile", "Executive"))); onActivated: root.settings.setValue("coach/profile", currentText) }; Label { text: root.t("Proaktivitás", "Proactivity") }; ComboBox { model: ["Silent", "Advisory", "Balanced", "Proactive", "Strict"]; Component.onCompleted: currentIndex = Math.max(0, model.indexOf(root.settings.value("coach/proactivity", "Balanced"))); onActivated: root.settings.setValue("coach/proactivity", currentText) }; Label { text: root.t("Check-in", "Check-ins") }; Switch { checked: root.settings.value("coach/checkIns", true); onToggled: root.settings.setValue("coach/checkIns", checked) }; Label { text: root.t("Projekt awareness", "Project awareness") }; Switch { checked: root.settings.value("coach/projectAwareness", true); onToggled: root.settings.setValue("coach/projectAwareness", checked) }; Label { text: root.t("Mentor referral", "Mentor referrals") }; Switch { checked: root.settings.value("coach/mentorReferrals", true); onToggled: root.settings.setValue("coach/mentorReferrals", checked) }; Label { text: "Quiet hours" }; TextField { text: root.settings.value("coach/quietHours", "20:00-08:00"); onEditingFinished: root.settings.setValue("coach/quietHours", text) } } } } }
            ScrollView { contentWidth: availableWidth; ColumnLayout { width: parent.width; anchors.margins: 24; spacing: 16; Title { title: root.t("Haladó", "Advanced"); subtitle: root.t("Lokális GUI state és diagnosztikai beállítások. Canonical state-et nem töröl.", "Local GUI state and diagnostics. This never deletes canonical state.") }; Card { Layout.fillWidth: true; Layout.preferredHeight: 240 * root.uiScale; ColumnLayout { anchors.fill: parent; anchors.margins: 18; spacing: 10; Label { text: root.settings.configFilePath; color: root.textMuted; Layout.fillWidth: true; elide: Text.ElideMiddle }; Button { text: root.t("Megjelenés alaphelyzetbe", "Reset appearance"); onClicked: root.settings.resetGroup("appearance") }; Button { text: root.t("Mentor preferenciák alaphelyzetbe", "Reset Mentor preferences"); onClicked: root.settings.resetGroup("mentor") }; Button { text: root.t("Coach preferenciák alaphelyzetbe", "Reset Coach preferences"); onClicked: root.settings.resetGroup("coach") }; Button { text: root.t("Minden GUI-beállítás alaphelyzetbe…", "Reset all GUI settings…"); onClicked: resetDialog.open() } } } } }
        }
    }
    Dialog { id: resetDialog; title: root.t("GUI-beállítások visszaállítása", "Reset GUI settings"); modal: true; anchors.centerIn: parent; standardButtons: Dialog.Ok | Dialog.Cancel; Label { width: 440; wrapMode: Text.WordWrap; text: root.t("Ez csak a Control Center lokális felhasználói preferenciáit törli. Canonical, Evidence, Memory vagy projektadatot nem módosít.", "This clears only local Control Center preferences. Canonical, Evidence, Memory and project data are not modified.") }; onAccepted: root.settings.resetAll() }
}
