#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import tempfile
from pathlib import Path
from typing import Any, Callable

from fa3_buzz_runtime_admission import AdmissionDenied, MCP_AUTHORITY, PROVIDER_ID, SECURITY_AUTHORITY, WRAPPER_PROTOCOL, admit_secret_handle, apply_authorized_mutation, derive_tenant_context, direct_buzz_dev_mcp_allowed, discover_provider_candidates, lifecycle_transition, mutation_proposal, negotiate_provider, rederive_remote_target_path, resolve_workspace_target, run_ci_wrapper_contract_e2e, sanitize_provider_output, select_staged_candidate, validate_delegated_context, validate_execution_budget, validate_runtime_route

CONTRACT_ID = "FA3-BUZZ-RUNTIME-ADMISSION-CONTRACTS-001"
ADMISSION_ID = "FA3-BUZZ-RUNTIME-ADMISSION-001"
GATE_ID = "FA3-BUZZ-WRAPPER-GATESET-001"
GATE_RECORD_ID = "FA3-GATE-BUZZ-RUNTIME-ADMISSION-001"
DECISION_ID = "FA3-DEC-BUZZ-RUNTIME-ADMISSION-2026-09-07"
REFERENCE_ID = "FA3-BUZZ-RUNTIME-UPSTREAM-REFERENCE-2026-09-07"
EVIDENCE_ID = "FA3-EVID-BUZZ-RUNTIME-ADMISSION-CI-2026-09-07"
CAPABILITY_COUNT = 143
UPSTREAM_TAG = "desktop-v0.5.23"
UPSTREAM_COMMIT = "b9392d9d78744df365f9276e1ffe8c1baa5ea903"

P0_RULES = ["BUZZ_RUNTIME_PROVIDER_NOT_AUTHORITY","BUZZ_RAW_DEV_MCP_DIRECT_HOST_TOOL_DENIED","BUZZ_CENTRAL_MCP_GATEWAY_WRAPPER_REQUIRED","BUZZ_PROVIDER_DISCOVERY_MUST_NOT_EXECUTE","BUZZ_PROVIDER_PATH_AND_DIGEST_REVALIDATION_REQUIRED","BUZZ_PROVIDER_SHADOWING_FAIL_CLOSED_DIAGNOSABLE","BUZZ_PROTOCOL_NEGOTIATION_BEFORE_SECRET_OR_CAPABILITY_TRANSFER","BUZZ_RAW_PRIVATE_KEY_TRANSFER_FORBIDDEN","BUZZ_LEASED_SCOPED_SECRET_HANDLE_REQUIRED","BUZZ_DELEGATED_CALLER_CONTEXT_AND_CAPABILITY_NARROWING_REQUIRED","BUZZ_OWNER_ATTESTATION_NOT_AUTHORIZATION_LEASE","BUZZ_WORKSPACE_CANONICAL_PATH_REVALIDATION_REQUIRED","BUZZ_SYMLINK_ESCAPE_AND_RACE_FAIL_CLOSED","BUZZ_READ_DIFF_AUTH_APPLY_VERIFY_REQUIRED","BUZZ_STALE_OR_AMBIGUOUS_MUTATION_DENIED","BUZZ_EXTERNAL_EXECUTION_BOUNDED_AND_PROCESS_TREE_CANCELLABLE","BUZZ_PROVIDER_OUTPUT_HOSTILE_BOUNDED_REDACTED","BUZZ_TENANT_CONTEXT_SERVER_OWNED","BUZZ_REMOTE_TARGET_PATH_REDERIVED","BUZZ_INTENTIONAL_STOP_FINAL","BUZZ_CURRENT_HOST_PASS_NOT_FABRICATED_BY_CI","BUZZ_DISABLED_PROVIDER_ZERO_RUNTIME_COST_NONBLOCKING"]

def loadj(path: Path) -> dict[str, Any]: return json.loads(path.read_text(encoding="utf-8"))
def writej(path: Path, obj: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True); path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
def finding(code: str, message: str, **extra: Any) -> dict[str, Any]: return {"code": code, "severity": "P0", "message": message, **extra}
def _expect_denied(fn: Callable[[], Any]) -> bool:
    try: fn()
    except AdmissionDenied: return True
    return False

def reference_check(root: Path) -> dict[str, Any]:
    paths={"provider":root/"canonical/providers/FA3-PROVIDER-BUZZ-001.json","parent_enforcement":root/"canonical/buzz-enforcement.json","contracts":root/"canonical/contracts/FA3-BUZZ-RUNTIME-ADMISSION-CONTRACTS-001.json","admission":root/"canonical/buzz-runtime-admission.json","enforcement":root/"canonical/buzz-runtime-admission-enforcement.json","decision":root/"canonical/decisions/FA3-DEC-BUZZ-RUNTIME-ADMISSION-2026-09-07.json","reference":root/"canonical/references/FA3-BUZZ-RUNTIME-UPSTREAM-REFERENCE-2026-09-07.json","gate_record":root/"canonical/FA3-GATE-BUZZ-RUNTIME-ADMISSION-001.json","evidence":root/"evidence/reference/buzz-runtime-admission-ci-2026-09-07.json","runtime":root/"src/fa3_buzz_runtime_admission.py","gate":root/"src/fa3_buzz_runtime_admission_gate.py","test":root/"tests/test_buzz_runtime_admission_gate.py","runner":root/"bin/fa3-buzz-runtime-admission-gate","workflow":root/".github/workflows/fa3-buzz-runtime-admission.yml","docs":root/"docs/buzz-runtime-admission.md"}
    findings=[]
    for name,path in paths.items():
        if not path.is_file(): findings.append(finding("BUZZ-RT-REF-001",f"missing {name} artifact",path=str(path.relative_to(root))))
    if findings:return {"result":"FAIL","findings":findings}
    provider=loadj(paths["provider"]); parent=loadj(paths["parent_enforcement"]); contracts=loadj(paths["contracts"]); admission=loadj(paths["admission"]); enforcement=loadj(paths["enforcement"]); decision=loadj(paths["decision"]); reference=loadj(paths["reference"]); gate_record=loadj(paths["gate_record"]); evidence=loadj(paths["evidence"]); workflow=paths["workflow"].read_text(encoding="utf-8"); runtime=provider.get("runtime_admission",{})
    if not(provider.get("id")==PROVIDER_ID and provider.get("canonical_root") is False and provider.get("architectural_authority") is False and provider.get("new_capability") is False and provider.get("capability_count")==CAPABILITY_COUNT and provider.get("global_runtime_promotion_required_when_disabled") is False and runtime.get("contract_id")==CONTRACT_ID and runtime.get("admission_id")==ADMISSION_ID and runtime.get("wrapper_gate_id")==GATE_ID and runtime.get("status")=="NOT_ADMITTED_PENDING_CURRENT_HOST" and runtime.get("direct_buzz_dev_mcp_host_tool_provider")=="DENY" and runtime.get("required_route")=="FA3_AUTH_MCP_GATEWAY_WRAPPED" and runtime.get("reference_version")==UPSTREAM_TAG and runtime.get("reference_commit")==UPSTREAM_COMMIT and runtime.get("current_host_production_evidence")=="NOT_CLAIMED" and runtime.get("runtime_required_for_global_promotion_when_disabled") is False): findings.append(finding("BUZZ-RT-REF-002","Buzz provider runtime-admission boundary drift"))
    if not(parent.get("gate_id")=="FA3-BUZZ-GATESET-001" and GATE_ID in parent.get("child_gates",[]) and parent.get("runtime_admission_contract_id")==CONTRACT_ID and parent.get("runtime_admission_id")==ADMISSION_ID and parent.get("fail_closed") is True): findings.append(finding("BUZZ-RT-REF-003","Buzz parent gate child/admission binding drift"))
    if not(contracts.get("id")==CONTRACT_ID and contracts.get("status")=="CANONICAL" and contracts.get("provider_id")==PROVIDER_ID and contracts.get("provider_neutral_semantics") is True and contracts.get("new_capability") is False and contracts.get("new_architectural_authority") is False and contracts.get("capability_count")==CAPABILITY_COUNT and contracts.get("capability_projection")==["CAP-008"] and "FA3-DESKTOP-AGENT-WORKBENCH-CONTRACTS-001" in contracts.get("parent_contracts",[]) and "FA3-AGENT-EXEC-CONTRACTS-001" in contracts.get("parent_contracts",[]) and contracts.get("mcp_and_tool_boundary",{}).get("canonical_authority")==MCP_AUTHORITY and contracts.get("mcp_and_tool_boundary",{}).get("raw_buzz_dev_mcp_direct_host_tool_provider")=="DENY" and contracts.get("mutation_semantics",{}).get("diff_before_apply") is True and contracts.get("secret_boundary",{}).get("raw_private_key_or_nsec_transfer")=="FORBIDDEN" and contracts.get("evidence",{}).get("current_host_activation_requires_real_e2e") is True): findings.append(finding("BUZZ-RT-REF-004","Buzz runtime admission contract drift"))
    pin=admission.get("immutable_reference",{})
    if not(admission.get("id")==ADMISSION_ID and admission.get("provider_id")==PROVIDER_ID and admission.get("contract_id")==CONTRACT_ID and admission.get("gate_id")==GATE_ID and admission.get("status")=="NOT_ADMITTED_PENDING_CURRENT_HOST" and admission.get("fail_closed") is True and admission.get("current_host_evidence_required") is True and admission.get("runtime_required_for_global_promotion_when_disabled") is False and pin.get("tag")==UPSTREAM_TAG and pin.get("commit")==UPSTREAM_COMMIT and admission.get("receipt")=="evidence/receipts/buzz-runtime-current-host.json" and admission.get("promotion_effect")=="NONE_UNTIL_SEPARATE_CURRENT_HOST_RUNTIME_ADMISSION_PASS"): findings.append(finding("BUZZ-RT-REF-005","Buzz runtime admission policy drift"))
    if not(enforcement.get("gate_id")==GATE_ID and enforcement.get("parent_gate_id")=="FA3-BUZZ-GATESET-001" and enforcement.get("provider_id")==PROVIDER_ID and enforcement.get("contract_id")==CONTRACT_ID and enforcement.get("admission_id")==ADMISSION_ID and enforcement.get("decision_id")==DECISION_ID and enforcement.get("fail_closed") is True and enforcement.get("runtime_provider_required_for_global_promotion_when_disabled") is False and enforcement.get("mandatory_rule_count")==len(P0_RULES) and enforcement.get("p0_invariants")==P0_RULES and enforcement.get("current_host_status")=="NOT_ADMITTED_PENDING_CURRENT_HOST"): findings.append(finding("BUZZ-RT-REF-006","Buzz wrapper enforcement rule-set drift"))
    if not(decision.get("id")==DECISION_ID and decision.get("status")=="CANONICAL_CLOSED" and decision.get("provider_id")==PROVIDER_ID and decision.get("contract_id")==CONTRACT_ID and decision.get("admission_id")==ADMISSION_ID and decision.get("gate_id")==GATE_ID and decision.get("new_capabilities")==0 and decision.get("new_architectural_authorities")==0 and decision.get("capability_count_after")==CAPABILITY_COUNT and decision.get("runtime_activation_status")=="NOT_ADMITTED_PENDING_CURRENT_HOST" and decision.get("authority_boundaries_unchanged") is True): findings.append(finding("BUZZ-RT-REF-007","Buzz runtime-admission decision drift"))
    release=reference.get("desktop_release",{})
    if not(reference.get("id")==REFERENCE_ID and reference.get("provider_id")==PROVIDER_ID and release.get("tag")==UPSTREAM_TAG and release.get("commit")==UPSTREAM_COMMIT and reference.get("current_host_runtime_promotion_claim") is False and reference.get("floating_main_allowed_for_runtime_promotion") is False): findings.append(finding("BUZZ-RT-REF-008","Buzz immutable upstream reference drift"))
    if not(gate_record.get("id")==GATE_RECORD_ID and gate_record.get("gateset_id")==GATE_ID and gate_record.get("provider_id")==PROVIDER_ID and gate_record.get("priority")=="P0" and gate_record.get("fail_closed") is True and gate_record.get("command")=="./bin/fa3-buzz-runtime-admission-gate" and gate_record.get("current_host_production_claim") is False and gate_record.get("capability_count")==CAPABILITY_COUNT and gate_record.get("new_capabilities")==0 and gate_record.get("new_architectural_authorities")==0): findings.append(finding("BUZZ-RT-REF-009","Buzz executable gate record drift"))
    if not(evidence.get("id")==EVIDENCE_ID and evidence.get("provider_id")==PROVIDER_ID and evidence.get("contract_id")==CONTRACT_ID and evidence.get("admission_id")==ADMISSION_ID and evidence.get("gate_id")==GATE_ID and evidence.get("status")=="PASS" and evidence.get("evidence_scope")=="CI_SYNTHETIC_WRAPPER_CONTRACT_AND_SECURITY_REGRESSION" and evidence.get("current_host_production_evidence") is False and evidence.get("current_host_runtime_status")=="NOT_ADMITTED_PENDING_CURRENT_HOST" and evidence.get("synthetic_provider_fixture") is True and evidence.get("raw_buzz_dev_mcp_direct_host_tool_provider")=="DENIED" and evidence.get("regression_case_count")==26 and evidence.get("new_capabilities")==0 and evidence.get("new_architectural_authorities")==0 and evidence.get("capability_count_after")==CAPABILITY_COUNT and evidence.get("promotion_effect")=="NONE"): findings.append(finding("BUZZ-RT-REF-010","Buzz CI reference evidence drift"))
    if not all(x in workflow for x in ("FA3 Buzz Runtime Admission","test_buzz_runtime_admission_gate.py","fa3-buzz-runtime-admission-gate","buzz-runtime-admission-gate-report.json")): findings.append(finding("BUZZ-RT-REF-011","Buzz permanent workflow binding drift"))
    return {"result":"PASS" if not findings else "FAIL","findings":findings}

def regression_check() -> dict[str, Any]:
    cases={}; digest="a"*64; base={"path":"/opt/fa3/staged/buzz-backend-reference","sha256":digest,"discovery_executed_provider":False}; good_route={"mcp_authority":MCP_AUTHORITY,"fa3_wrapper":True,"direct_buzz_dev_mcp":False,"workspace_containment":True,"capability_narrowing":True}
    cases["raw_buzz_dev_mcp_direct_denied"]=direct_buzz_dev_mcp_allowed() is False
    cases["wrapped_route_admitted"]=validate_runtime_route(good_route)["status"]=="ADMITTED_WRAPPED_ROUTE"
    cases["discovery_execution_denied"]=_expect_denied(lambda:discover_provider_candidates([{**base,"discovery_executed_provider":True}]))
    cases["provider_digest_mismatch_denied"]=_expect_denied(lambda:select_staged_candidate([base],selected_path=base["path"],staged_path="/opt/fa3/staged/buzz-backend-reference",staged_sha256="b"*64))
    cases["provider_shadowing_denied"]=_expect_denied(lambda:select_staged_candidate([base,dict(base)],selected_path=base["path"],staged_path="/opt/fa3/staged/buzz-backend-reference",staged_sha256=digest))
    staged=select_staged_candidate([base],selected_path=base["path"],staged_path="/opt/fa3/staged/buzz-backend-reference",staged_sha256=digest); info={"protocol":WRAPPER_PROTOCOL,"provider_id":PROVIDER_ID,"sha256":digest,"capabilities":["workspace.read","workspace.propose"]}; negotiated=negotiate_provider(staged,info,requested_capabilities=["workspace.read"])
    cases["protocol_negotiation_admitted"]=negotiated["status"]=="NEGOTIATED"; cases["capability_overrequest_denied"]=_expect_denied(lambda:negotiate_provider(staged,info,requested_capabilities=["host.shell"])); cases["raw_private_key_denied"]=_expect_denied(lambda:admit_secret_handle(negotiation=negotiated,secret={"type":"NSEC","capabilities":["workspace.read"],"expires_at":"2099"},requested_capabilities=["workspace.read"])); cases["scoped_secret_handle_admitted"]=admit_secret_handle(negotiation=negotiated,secret={"type":"LEASED_SCOPED_SECRET_HANDLE","handle_id":"fixture","capabilities":["workspace.read"],"expires_at":"2099-01-01T00:00:00Z"},requested_capabilities=["workspace.read"])["raw_secret_transferred"] is False
    delegated={"actor_id":"agent:test","owner_id":"owner:test","delegated_caller_context":{"actor_id":"agent:test","owner_id":"owner:test"},"capability_grant":{"capabilities":["workspace.read"]},"requested_capabilities":["workspace.read"],"owner_attestation":{"kind":"OWNER_ATTESTATION"}}
    cases["owner_attestation_only_denied"]=_expect_denied(lambda:validate_delegated_context(authorization_lease=None,**delegated)); cases["delegated_context_admitted"]=validate_delegated_context(authorization_lease={"issuer":SECURITY_AUTHORITY,"decision":"ALLOW","capabilities":["workspace.read"]},**delegated)["status"]=="DELEGATED_CONTEXT_ADMITTED"
    with tempfile.TemporaryDirectory() as td:
        root=Path(td); target=root/"work.txt"; target.write_text("alpha\n",encoding="utf-8"); cases["inside_workspace_path_admitted"]=resolve_workspace_target(root,"work.txt")==target.resolve(); cases["traversal_path_denied"]=_expect_denied(lambda:resolve_workspace_target(root,"../escape.txt")); outside=root.parent/f"{root.name}-outside"; outside.mkdir(exist_ok=True); outside_file=outside/"outside.txt"; outside_file.write_text("x",encoding="utf-8"); link=root/"escape"
        try: link.symlink_to(outside,target_is_directory=True); cases["symlink_escape_denied"]=_expect_denied(lambda:resolve_workspace_target(root,"escape/outside.txt"))
        finally:
            if link.exists() or link.is_symlink(): link.unlink()
            outside_file.unlink(missing_ok=True); outside.rmdir()
        proposal=mutation_proposal(root,"work.txt",old_text="alpha",new_text="beta"); cases["diff_before_apply_produced"]=bool(proposal["proposed_diff"] and proposal["applied"] is False and target.read_text(encoding="utf-8")=="alpha\n"); target.write_text("one one\n",encoding="utf-8"); cases["ambiguous_mutation_denied"]=_expect_denied(lambda:mutation_proposal(root,"work.txt",old_text="one",new_text="two")); target.write_text("alpha\n",encoding="utf-8"); proposal=mutation_proposal(root,"work.txt",old_text="alpha",new_text="beta"); target.write_text("changed\n",encoding="utf-8"); cases["stale_apply_denied"]=_expect_denied(lambda:apply_authorized_mutation(root,proposal,{"issuer":SECURITY_AUTHORITY,"decision":"ALLOW","proposed_diff_sha256":proposal["proposed_diff_sha256"]})); target.write_text("alpha\n",encoding="utf-8"); proposal=mutation_proposal(root,"work.txt",old_text="alpha",new_text="beta"); receipt=apply_authorized_mutation(root,proposal,{"issuer":SECURITY_AUTHORITY,"decision":"ALLOW","proposed_diff_sha256":proposal["proposed_diff_sha256"]}); cases["authorized_atomic_apply_verified"]=receipt["status"]=="APPLIED_AND_VERIFIED" and target.read_text(encoding="utf-8")=="beta\n"; remote=root/"remote"; remote.mkdir(); cases["host_path_remote_cross_boundary_denied"]=_expect_denied(lambda:rederive_remote_target_path(target_root=remote,relative_path="x",host_resolved_path="/host/work/x"))
    cases["unbounded_execution_denied"]=_expect_denied(lambda:validate_execution_budget({"argv":["buzz-backend","run"],"shell":False,"timeout_seconds":9999,"output_limit_bytes":4096,"process_tree_cancellation":True})); cases["bounded_execution_admitted"]=validate_execution_budget({"argv":["buzz-backend","info"],"shell":False,"timeout_seconds":5,"output_limit_bytes":4096,"process_tree_cancellation":True})["status"]=="BOUNDED_EXECUTION_ADMITTED"; sanitized=sanitize_provider_output("token=supersecret",output_limit_bytes=4096,secrets=["supersecret"]); cases["hostile_output_bounded_redacted"]=sanitized["trusted"] is False and "supersecret" not in sanitized["text"] and "[REDACTED]" in sanitized["text"]; cases["tenant_spoof_denied"]=_expect_denied(lambda:derive_tenant_context(server_tenant="community-a",client_tenant="community-b")); cases["server_owned_tenant_admitted"]=derive_tenant_context(server_tenant="community-a",client_tenant="community-a")["source"]=="SERVER_DERIVED"; cases["intentional_stop_final"]=lifecycle_transition(event="INTENTIONAL_STOP")=={"state":"STOPPED_FINAL","restart":False}; ci=run_ci_wrapper_contract_e2e(); cases["ci_fixture_cannot_claim_current_host"]=ci["result"]=="PASS" and ci["synthetic_provider_fixture"] is True and ci["current_host_production_claim"] is False
    passed=sum(bool(v) for v in cases.values()); return {"schema":"fa3.buzz-runtime-admission-regression.v1","result":"PASS" if passed==len(cases)==26 else "FAIL","passed":passed,"total":len(cases),"cases":cases,"ci_wrapper_contract_e2e":ci}

def gate(root: Path) -> dict[str, Any]:
    root=Path(root).resolve(); reference=reference_check(root); regressions=regression_check(); ok=reference["result"]=="PASS" and regressions["result"]=="PASS"; report={"schema":"fa3.buzz-runtime-admission-gate-report.v1","gate_id":GATE_ID,"parent_gate_id":"FA3-BUZZ-GATESET-001","provider_id":PROVIDER_ID,"contract_id":CONTRACT_ID,"admission_id":ADMISSION_ID,"result":"PASS" if ok else "FAIL","reference":reference,"regressions":regressions,"p0_rule_count":len(P0_RULES),"p0_rules":P0_RULES,"raw_buzz_dev_mcp_direct_host_tool_provider":"DENIED","runtime_status":"NOT_ADMITTED_PENDING_CURRENT_HOST","current_host_production_evidence":False,"new_capabilities":0,"new_architectural_authorities":0,"capability_count":CAPABILITY_COUNT,"promotion_effect":"NONE_UNTIL_REAL_CURRENT_HOST_E2E"}; writej(root/"reports/buzz-runtime-admission-gate-report.json",report); return report

def main()->int:
    ap=argparse.ArgumentParser(description="FA3 Buzz safe runtime-admission wrapper gate"); ap.add_argument("--root",default=str(Path(__file__).resolve().parents[1])); args=ap.parse_args(); result=gate(Path(args.root)); print(json.dumps(result,indent=2)); return 0 if result["result"]=="PASS" else 2
if __name__=="__main__": raise SystemExit(main())
