#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
from typing import Any
from fa3_ai_comms import CommunicationDenied
from fa3_orchestration_provider_spi import ProviderAdapterError,ProviderParticipantExpansionDenied,ProviderRuntimeNotPromoted,compile_plan_envelopes,compile_provider_envelope,load_spi_contract,validate_provider_message
from fa3_orchestration_workforce import DecisionAdvisoryError,compile_cross_domain_plan,load_registry,route_task
from fa3_release_baseline import load_active_release_baseline
from fa3_uaf import ActionRegistry
PROFILE_REL=Path("canonical/profiles/FA3-ORCHESTRATION-WORKFORCE-001.json");CONTRACT_REL=Path("canonical/contracts/FA3-ORCHESTRATION-WORKFORCE-CONTRACTS-001.json");DECISION_REL=Path("canonical/decisions/FA3-DEC-ORCHESTRATION-WORKFORCE-2026-09-15.json");ASSESSMENT_REL=Path("canonical/assessments/FA3-ORCHESTRATION-WORKFORCE-DECISION-ASSESSMENT-2026-09-23.json");ADMISSION_REL=Path("canonical/contracts/FA3-ORCHESTRATION-PROVIDER-CURRENT-HOST-ADMISSION-001.schema.json");REPORT_REL=Path("reports/orchestration-workforce-gate-report.json")
PROVIDERS={"FA3-PROVIDER-CREWAI-001","FA3-PROVIDER-CONDUCTOR-001","FA3-PROVIDER-OPEN-MULTI-AGENT-001","FA3-PROVIDER-LANGGRAPH-001","FA3-PROVIDER-KESTRA-001","FA3-PROVIDER-PIPECAT-001","FA3-PROVIDER-N8N-001","FA3-PROVIDER-HAYSTACK-001"}
ACTIONS={"orchestration.plan","orchestration.delegate","orchestration.execute","orchestration.cancel","orchestration.resume","orchestration.inspect"}
ROUTES=[({"task_id":"durable","domain":"durable-workflow","required_capabilities":["durable_lifecycle"]},"FA3-SPECIALIST-DURABLE-LIFECYCLE-001"),({"task_id":"creative","domain":"media-production","required_capabilities":["media_production_planning","creative_team_planning"]},"FA3-MEDIA-PRODUCTION-DIRECTOR-001"),({"task_id":"job","domain":"media-job","required_capabilities":["adaptive_job_graph","media_batch_job"]},"FA3-SPECIALIST-ADAPTIVE-JOB-GRAPH-001"),({"task_id":"governed","domain":"governed-agent-team","required_capabilities":["governed_agent_team","execution_journal"]},"FA3-SPECIALIST-GOVERNED-AGENT-TEAM-001"),({"task_id":"graph","domain":"stateful-agent-graph","required_capabilities":["stateful_agent_graph","conditional_edges"]},"FA3-SPECIALIST-STATEFUL-AGENT-GRAPH-001"),({"task_id":"ingest","domain":"event-ingest","required_capabilities":["event_ingest","file_arrival_trigger"]},"FA3-SPECIALIST-EVENT-INGEST-001"),({"task_id":"live","domain":"realtime-multimodal","required_capabilities":["realtime_multimodal","audio_video_streaming"]},"FA3-SPECIALIST-REALTIME-MULTIMODAL-001"),({"task_id":"integration","domain":"integration","required_capabilities":["integration_workflow","webhook"]},"FA3-SPECIALIST-INTEGRATION-001"),({"task_id":"knowledge","domain":"knowledge","required_capabilities":["rag_pipeline","retrieval"]},"FA3-SPECIALIST-KNOWLEDGE-001")]
def load(p):return json.loads(p.read_text(encoding="utf-8"))
def finding(c,m,**d):return {"code":c,"severity":"P0","message":m,**d}
def chk(ok,f,c,m,**d):
    if not ok:f.append(finding(c,m,**d))
def receipt(pid):return {"schema":"fa3.orchestration-provider-current-host-admission.v1","provider_id":pid,"scope_id":"REFERENCE_TEST_ONLY","status":"ADMITTED","evidence_level":"CURRENT_HOST_PRODUCTION_E2E_PASS","runtime_identity":{"reference_test_fixture":True},"production_e2e":{"result":"PASS","evidence_refs":["REFERENCE_TEST_FIXTURE_NOT_RUNTIME_EVIDENCE"]},"global_promotion_claim":False}
def gate(root):
    root=Path(root).resolve();f=[];count=load_active_release_baseline(root).capability_count
    p,c,d,a,s=load(root/PROFILE_REL),load(root/CONTRACT_REL),load(root/DECISION_REL),load(root/ASSESSMENT_REL),load(root/ADMISSION_REL);reg=load_registry(root);spi=load_spi_contract(root)
    chk(p.get("status")=="CANONICAL" and p.get("priority")=="P0" and p.get("requirement")=="MUST",f,"ORCH-001","profile state invalid");chk(p.get("capability_count")==count and not p.get("new_capability") and not p.get("new_architectural_authority"),f,"ORCH-002","capability/authority drift");chk(d.get("reconciliation",{}).get("agent_native_uaf")=="MANDATORY_TYPED_ACTION_EXECUTION_BOUNDARY",f,"ORCH-003","UAF reconciliation missing");chk(spi.get("execution_boundary",{}).get("fabric")=="FA3-UNIFIED-ACTION-FABRIC-001" and spi.get("execution_boundary",{}).get("direct_provider_invocation") is False,f,"ORCH-004","SPI UAF boundary invalid");chk("FA3-AUTH-HOST-RESOURCE-BROKER-001" not in spi.get("adapter_kinds",{}),f,"ORCH-005","HRB exposed as provider adapter")
    durable=[x for x in reg["specialists"] if "durable_lifecycle" in set(x.get("authority_scope",[]))];resources=[x for x in reg["specialists"] if "host_resource" in set(x.get("authority_scope",[])) or x.get("id")=="FA3-SPECIALIST-RESOURCE-GOVERNANCE-001"];chk(len(durable)==1 and durable[0].get("provider")=="Temporal",f,"ORCH-006","Temporal authority drift");chk(not resources,f,"ORCH-007","HRB must be horizontal")
    fabrics={x.get("fabric") for x in reg.get("horizontal_fabrics",[])};chk({"FA3-UNIFIED-ACTION-FABRIC-001","FA3-AI-COMMS-001","FA3-DECISION-FABRIC-001","FA3-HARDWARE-DISCOVERY-CONTRACTS-001"}.issubset(fabrics),f,"ORCH-008","horizontal fabric bindings incomplete")
    roleproj=reg.get("role_definition_projection",{});chk(roleproj.get("registry_id")=="FA3-AGENT-DEFINITION-REGISTRY-001" and roleproj.get("contract_id")=="FA3-AGENT-DEFINITION-CONTRACTS-001" and roleproj.get("may_decorate_selected_specialist") is True and roleproj.get("may_expand_specialist_set") is False and roleproj.get("may_select_provider") is False and roleproj.get("may_override_hard_filters") is False and roleproj.get("may_expand_authorized_ai_participant_set") is False and roleproj.get("may_grant_capability_tool_model_secret_or_resource_access") is False,f,"ORCH-028","role-definition projection authority boundary invalid")
    for pid in sorted(PROVIDERS):
        x=load(root/"canonical/providers"/f"{pid}.json");chk(x.get("runtime_promotion_status")=="PENDING_CURRENT_HOST",f,"ORCH-009","provider promotion claimed",provider_id=pid);chk(x.get("execution_boundary",{}).get("direct_agent_provider_bypass") is False and x.get("ai_communication",{}).get("private_model_language_allowed") is False and x.get("ai_communication",{}).get("participant_set_expansion_allowed") is False,f,"ORCH-010","provider boundary invalid",provider_id=pid);chk(x.get("runtime_admission",{}).get("static_runtime_promotion_status_is_authority") is False and x.get("hardware_boundary",{}).get("accelerator_cardinality")=="0..N" and x.get("hardware_boundary",{}).get("cpu_only_host_valid") is True,f,"ORCH-011","provider runtime/hardware boundary invalid",provider_id=pid)
    chk(a.get("assessment")=="REQUIRED" and a.get("project_radar_checked") is True and {"FA3-ORCHESTRATION-WORKFORCE-001",*PROVIDERS}.issubset(set(a.get("covered_ids",[]))),f,"ORCH-012","Decision Fabric assessment invalid");chk(s.get("x-fa3-contract-id")=="FA3-ORCHESTRATION-PROVIDER-CURRENT-HOST-ADMISSION-001",f,"ORCH-013","admission schema invalid")
    amap={x.action_id:x for x in ActionRegistry.from_directory(root/"canonical/actions").list()};chk(ACTIONS.issubset(amap),f,"ORCH-014","UAF action set incomplete")
    for aid in ACTIONS&set(amap):chk(amap[aid].security.get("authentication")=="required" and amap[aid].security.get("authorization")=="required" and amap[aid].evidence.get("required") is True and amap[aid].resources.get("accelerator",{}).get("cardinality")=="0..N",f,"ORCH-015","action boundary invalid",action_id=aid)
    for task,expected in ROUTES:
        x=route_task(root,task);chk(x.get("status")=="ROUTED" and x.get("specialist_id")==expected,f,"ORCH-016","route mismatch",task=task,actual=x)
    chk(route_task(root,{"task_id":"resource","domain":"resource-governance","required_capabilities":["host_resource_admission"],"required_authorities":["host_resource"]}).get("status")=="HUMAN_ESCALATION",f,"ORCH-017","resource routed as specialist")
    neg=route_task(root,{"task_id":"accel","domain":"media-production","required_capabilities":["media_production_planning","accelerator_placement"]});rej={x["specialist_id"]:x["reasons"] for x in neg.get("rejected",[])};chk(any(r.startswith("ANTI_CAPABILITY:accelerator_placement") for r in rej.get("FA3-MEDIA-PRODUCTION-DIRECTOR-001",[])),f,"ORCH-018","accelerator placement not blocked")
    task={"task_id":"creative-runtime","domain":"media-production","required_capabilities":["media_production_planning","creative_team_planning"],"authorized_ai_participants":["primary-model","partner-model"]};chk(route_task(root,task,runtime_execution=True).get("status")=="HUMAN_ESCALATION",f,"ORCH-019","runtime selected without receipt");admitted=route_task(root,task,runtime_execution=True,admission_receipts={"FA3-PROVIDER-CREWAI-001":receipt("FA3-PROVIDER-CREWAI-001")});chk(admitted.get("provider_id")=="FA3-PROVIDER-CREWAI-001",f,"ORCH-020","receipt admission wiring failed")
    design=route_task(root,task);proj=compile_provider_envelope(root,task,design);chk(proj.get("uaf_action",{}).get("action_id")=="orchestration.delegate" and proj.get("direct_runtime_invocation_allowed") is False,f,"ORCH-021","UAF projection invalid")
    try:compile_provider_envelope(root,task,design,runtime_execution=True);f.append(finding("ORCH-022","runtime projection bypassed receipt"))
    except ProviderRuntimeNotPromoted:pass
    exp=dict(task);exp["metadata"]={"provider_requested_ai_participants":["unauthorized-model"]}
    try:compile_provider_envelope(root,exp,route_task(root,exp));f.append(finding("ORCH-023","participant expansion allowed"))
    except ProviderParticipantExpansionDenied:pass
    dm=dict(task);dm["metadata"]={"direct_model_provider":"provider-native"}
    try:compile_provider_envelope(root,dm,route_task(root,dm));f.append(finding("ORCH-024","direct model routing allowed"))
    except ProviderAdapterError:pass
    msg={"communication_mode":"HUMAN_LANGUAGE","language_tag":"en-US","human_readable_text":"Return the delegated task result with evidence references.","human_readable_authoritative":True};validate_provider_message(msg,sender="a",recipient="b");bad=dict(msg);bad["codebook"]={"zx":"hidden"}
    try:validate_provider_message(bad,sender="a",recipient="b");f.append(finding("ORCH-025","private codebook allowed"))
    except CommunicationDenied:pass
    at={"task_id":"advisory","domain":"media-production","required_capabilities":["media_production_planning"]};ids=route_task(root,at)["decision_fabric"]["candidate_ids"];adv={"authority":False,"candidate_set_expanded":False,"candidate_ids":[*ids,"FA3-UNAUTHORIZED"],"selected_specialist_id":"FA3-UNAUTHORIZED","rollout":"ACTIVE","status":"DECIDED"}
    try:route_task(root,at,decision_advisory=adv);f.append(finding("ORCH-026","Decision Fabric expanded candidate set"))
    except DecisionAdvisoryError:pass
    req=load(root/"examples/orchestration-workforce-media.json");plan=compile_cross_domain_plan(root,req);ap=compile_plan_envelopes(root,req,plan);chk(plan.get("status")=="READY" and len(plan["decisions"])==4 and all(e.get("uaf_action",{}).get("action_id")=="orchestration.delegate" for e in ap["envelopes"]),f,"ORCH-027","media/UAF plan invalid")
    report={"schema":"fa3.orchestration-workforce-gate-report.v2","profile_id":p.get("id"),"result":"PASS" if not f else "FAIL","blocking_findings":len(f),"findings":f,"details":{"capability_count":count,"specialist_count":len(reg["specialists"]),"runtime_provider_promotion_claimed":False,"reference_receipt_is_runtime_evidence":False,"resource_authority":"FA3-AUTH-HOST-RESOURCE-BROKER-001_HORIZONTAL_ONLY","decision_fabric_role":"OPTIONAL_ADVISORY_AFTER_DETERMINISTIC_ELIGIBILITY","ai_communication_policy":"FA3-AI-COMMS-001"}}
    out=root/REPORT_REL;out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(report,indent=2)+"\n",encoding="utf-8");return report
def main():
    p=argparse.ArgumentParser();p.add_argument("--root",default=str(Path(__file__).resolve().parents[1]));a=p.parse_args();r=gate(a.root);print(json.dumps(r,indent=2));return 0 if r["result"]=="PASS" else 2
if __name__=="__main__":raise SystemExit(main())
