#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PROFILE="canonical/profiles/FA3-SECRET-BROKER-001.json"
CONTRACT="canonical/contracts/FA3-SECRET-BROKER-CONTRACTS-001.json"
DECISION="canonical/decisions/FA3-DEC-SECRET-BROKER-ENCRYPTED-VAULT-2026-09-20.json"
ENFORCEMENT="canonical/secret-broker-enforcement.json"
CONFORMANCE="canonical/FA3-SECRET-BROKER-RUNTIME-CONFORMANCE-001.json"
GATE="canonical/FA3-GATE-SECRET-BROKER-001.json"
def load(path:str):return json.loads((ROOT/path).read_text())
def check()->dict:
    findings=[]
    def req(ok:bool,code:str):
        if not ok:findings.append(code)
    p,c,d,e,r,g=map(load,[PROFILE,CONTRACT,DECISION,ENFORCEMENT,CONFORMANCE,GATE])
    req(p.get("priority")=="P0" and p.get("requirement")=="MUST" and p.get("parent_profile")=="FA3-SCS-001","SB-001")
    req(p.get("provider_neutral") is True and p.get("architectural_authority") is False and p.get("new_capability") is False and p.get("new_architectural_authority") is False and p.get("capability_count")==143,"SB-002")
    machine=p.get("storage_classes",{}).get("machine_service",{})
    req(machine.get("default_type")=="LUKS2_FILE_IMAGE" and machine.get("default_image")=="/var/lib/fa3/state/fa3-machine-state.img" and machine.get("filesystem_label")=="FA3_MSTATE","SB-003")
    req(set(machine.get("mount_options",[]))=={"nodev","nosuid","noexec"} and machine.get("raw_mount_visible_to_consumers") is False and machine.get("external_naming_policy")=="GENERIC_NON_DISCLOSING" and machine.get("content_scope")=="FA3_CREDENTIAL_SECRETS_ONLY","SB-004")
    req(p.get("storage_classes",{}).get("user_session",{}).get("profile")=="FA3-SESSION-VAULT-001" and p["storage_classes"]["user_session"]["raw_machine_application_secret_storage"]=="FORBIDDEN","SB-005")
    req(p.get("unlock",{}).get("default")=="SYSTEMD_ENCRYPTED_CREDENTIAL" and p["unlock"]["systemd_credential_key_mode"]=="host" and p["unlock"]["implicit_tpm_binding"]=="FORBIDDEN_BY_DEFAULT" and p["unlock"]["plaintext_keyfile_persistence"]=="FORBIDDEN" and p["unlock"]["unlock_secret_inside_same_image"]=="FORBIDDEN","SB-006")
    req(p.get("delivery",{}).get("broker_transport")=="LOCAL_UNIX_DOMAIN_SOCKET_WITH_SO_PEERCRED" and p["delivery"]["podman_env_secret"]=="FORBIDDEN_BY_DEFAULT" and p["delivery"]["bulk_export"]=="FORBIDDEN" and p["delivery"]["full_vault_bind_mount"]=="FORBIDDEN","SB-007")
    req(p.get("backend_adapters",{}).get("infisical",{}).get("targeted_get_only") is True and p["backend_adapters"]["podman_secret"]["default_store_ram_only_claim"]=="FORBIDDEN_WITHOUT_EVIDENCE","SB-007A")
    req(p.get("portability",{}).get("hardware_vendor_neutral") is True and p["portability"]["accelerator_requirement"]=="NONE" and p["portability"].get("desktop_environment_required") is False and p["portability"].get("display_server_required") is False and p["portability"].get("gui_required") is False,"SB-008")
    req(c.get("id")=="FA3-SECRET-BROKER-CONTRACTS-001" and "SecretReference" in c.get("contracts",[]) and "SecretProjectionLease" in c.get("contracts",[]) and "secret_kind" in c.get("required_fields",{}).get("SecretReference",[]),"SB-009")
    req("SECRET_VALUE_NEVER_IN_LONG_LIVED_ENVIRONMENT" in c.get("invariants",[]) and "SAME_UID_DESKTOP_PROCESS_ISOLATION_MUST_NOT_BE_OVERCLAIMED" in c.get("invariants",[]) and "VAULT_CONTENT_SCOPE_CREDENTIAL_SECRETS_ONLY" in c.get("invariants",[]) and "DESKTOP_ENVIRONMENT_NOT_CANONICAL_DEPENDENCY" in c.get("invariants",[]) and "EXACTLY_ONE_ACTIVE_POLICY_PER_SECRETREF_WHEN_ACCESS_IS_ENABLED" in c.get("invariants",[]) and "MACHINE_SECRET_CONSUMER_IDENTITY_MUST_HAVE_BROKER_SOCKET_TRANSPORT_ACCESS" in c.get("invariants",[]) and "SECRET_DEPENDENT_PROVIDER_MUST_STOP_WITH_FA3_SECRETS_TARGET" in c.get("invariants",[]) and "CURRENT_HOST_RUNNER_REMAINS_NON_ROOT" in c.get("invariants",[]) and "CURRENT_HOST_PRIVILEGED_E2E_EXACT_ROOT_HELPER_ONLY" in c.get("invariants",[]) and "GENERAL_PASSWORDLESS_SUDO_FOR_RUNNER_FORBIDDEN" in c.get("invariants",[]) and "CURRENT_HOST_PRIVILEGED_PACKAGE_SOURCE_COMMIT_REQUIRED" in c.get("invariants",[]) and "VAULT_FILESYSTEM_MOUNT_MUST_BE_SYSTEMD_MOUNT_UNIT_IN_MANAGER_NAMESPACE" in c.get("invariants",[]) and "CREDENTIAL_SERVICE_MUST_NOT_OWN_HOST_FILESYSTEM_MOUNT" in c.get("invariants",[]) and "MAPPER_SERVICE_CAPABILITY_SET_MUST_NOT_EXCEED_CAP_SYS_ADMIN" in c.get("invariants",[]) and "BROKER_START_REQUIRES_REAL_VAULT_MOUNTPOINT" in c.get("invariants",[]) and "FAILED_CURRENT_HOST_SYSTEMD_E2E_MUST_NOT_LEAVE_EPHEMERAL_LUKS_MAPPING_OPEN" in c.get("invariants",[]),"SB-010")
    req(d.get("status")=="CANONICAL_CLOSED" and d.get("new_capabilities")==0 and d.get("new_architectural_authorities")==0 and d.get("capability_count_after")==143 and "SECRETS_CORE_HEADLESS_DESKTOP_AND_DISPLAY_SERVER_AGNOSTIC" in d.get("constraints",[]) and "REAL_CURRENT_HOST_SYSTEMD_TARGET_START_AND_EXIT_REQUIRED" in d.get("constraints",[]),"SB-011")
    req(e.get("fail_closed") is True and e.get("mandatory_rule_count")==58 and len(e.get("p0_invariants",[]))==58,"SB-012")
    req("PODMAN_SECRET_TYPE_ENV_FORBIDDEN_BY_DEFAULT" in e["p0_invariants"] and "REAL_CURRENT_HOST_E2E_REQUIRED_FOR_RUNTIME_PROMOTION" in e["p0_invariants"] and "INFISICAL_TARGETED_GET_ONLY_BULK_EXPORT_FORBIDDEN" in e["p0_invariants"] and "PODMAN_SECRET_STORE_RAM_ONLY_CLAIM_REQUIRES_EVIDENCE" in e["p0_invariants"] and "VAULT_CONTENT_SCOPE_CREDENTIAL_SECRETS_ONLY" in e["p0_invariants"] and "SECRET_KIND_CANONICAL_ALLOWLIST_REQUIRED" in e["p0_invariants"] and "DESKTOP_ENVIRONMENT_NOT_CANONICAL_DEPENDENCY" in e["p0_invariants"] and "FA3_EXIT_MUST_STOP_SECRET_LIFECYCLE" in e["p0_invariants"] and "FA3_EXIT_REQUIRES_BROKER_INACTIVE_VAULT_UNMOUNTED_AND_LUKS_CLOSED" in e["p0_invariants"] and "SECRET_ROTATION_ATOMIC_VERSIONED_REPLACEMENT_REQUIRED" in e["p0_invariants"] and "SECRET_REVOCATION_REMOVES_ACTIVE_OBJECT" in e["p0_invariants"] and "ADMIN_METADATA_LIST_MUST_NOT_RETURN_SECRET_VALUES" in e["p0_invariants"] and "BACKUP_REQUIRES_CLOSED_VAULT_AND_OPAQUE_LUKS2_COPY" in e["p0_invariants"] and "RESTORE_REQUIRES_HEALTH_VALIDATION_AND_FINAL_CLOSED_STATE" in e["p0_invariants"] and "DUPLICATE_POLICY_FOR_SECRETREF_DENIED_FAIL_CLOSED" in e["p0_invariants"] and "MACHINE_SECRET_CONSUMER_MUST_HAVE_SECRET_CLIENT_TRANSPORT_MEMBERSHIP" in e["p0_invariants"] and "SECRET_DEPENDENT_PROVIDER_MUST_BE_PART_OF_FA3_SECRETS_TARGET" in e["p0_invariants"] and "FA3_EXIT_REQUIRES_SECRETS_TARGET_INACTIVE" in e["p0_invariants"] and "SYSTEMD_ENCRYPTED_CREDENTIAL_DEFAULT_KEY_MODE_HOST" in e["p0_invariants"] and "IMPLICIT_TPM2_BINDING_FORBIDDEN_BY_DEFAULT" in e["p0_invariants"] and "LUKS_UNLOCK_KEY_ROTATION_TWO_PHASE_REQUIRED" in e["p0_invariants"] and "LUKS_UNLOCK_REKEY_SUCCESS_REQUIRES_FINAL_CLOSED_STATE" in e["p0_invariants"] and "CURRENT_HOST_PRIVILEGED_E2E_EXACT_ROOT_HELPER_ONLY" in e["p0_invariants"] and "CURRENT_HOST_PRIVILEGED_E2E_SOURCE_COMMIT_BOUND" in e["p0_invariants"],"SB-013")
    req(r.get("status")=="MATERIALIZED_PENDING_REAL_CURRENT_HOST_EXECUTION" and r.get("production_runtime_promoted") is False and r.get("global_promotion_claim") is False and all(x in r.get("required_checks",[]) for x in ["ENCRYPTED_SYSTEMD_UNLOCK_RUNTIME_PASS","SYSTEMD_TARGET_LIFECYCLE_EXIT_PASS","SYSTEMD_E2E_ARTIFACT_CLEANUP_PASS","POLICY_INSTALL_REMOVE_PASS","RESTORED_SECRET_VALUE_INTEGRITY_PASS","HARDWARE_NEUTRAL_SYSTEMD_CREDENTIAL_HOST_KEY_MODE","HOST_MOUNT_NAMESPACE_VISIBILITY_PASS","LUKS_UNLOCK_KEY_ROTATION_PASS","OLD_UNLOCK_KEY_REJECTED_AFTER_REKEY","NEW_UNLOCK_KEY_ACCEPTED_AFTER_REKEY","REKEY_FINAL_VAULT_STATE_CLOSED","CURRENT_HOST_PRIVILEGED_BRIDGE_SOURCE_BINDING_PASS","NON_ROOT_ADMIN_AUTHORIZATION_PASS","EPHEMERAL_ADMIN_PROBE_REMOVED_PASS"]),"SB-014")
    req(g.get("priority")=="P0" and g.get("fail_closed") is True and g.get("production_runtime_promoted") is False,"SB-015")
    broker=(ROOT/"src/fa3_secret_broker.py").read_text()
    req("SO_PEERCRED" in broker and "secret_ref_sha256" in broker and "secret_values_collected" in broker and "serve_forever" in broker and "ALLOWED_SECRET_KINDS" in broker and "credential secrets only" in broker and '"rotate"' in broker and '"revoke"' in broker and '"list_metadata"' in broker,"SB-016")
    req('if op=="bulk"' not in broker and "unsupported operation" in broker,"SB-017")
    client=(ROOT/"bin/fa3-secretctl").read_text()
    req("getpass.getpass" in client and "secret_b64" in client and "os.environ" not in client and '"rotate"' in client and '"revoke"' in client and '"list-metadata"' in client,"SB-018")
    init=(ROOT/"bin/fa3-secret-vault-init").read_text()
    req("systemd-creds encrypt" in init and "--with-key=host" in init and "--key-file -" in init and "FA3_MSTATE" in init,"SB-019")
    mount=(ROOT/"libexec/fa3-secret-vault-mount.sh").read_text()
    req('CREDENTIALS_DIRECTORY' in mount and "for o in nodev nosuid noexec" in mount and "cryptsetup close" in mount and "assert_closed" in mount,"SB-020")
    vault_unit=(ROOT/"deployment/secrets/fa3-secret-vault.service").read_text()
    mount_unit=(ROOT/"deployment/secrets/run-fa3-machine\\x2dstate.mount").read_text()
    broker_unit=(ROOT/"deployment/secrets/fa3-secret-broker.service").read_text()
    target=(ROOT/"deployment/secrets/fa3-secrets.target").read_text()
    vault_caps=p.get("lifecycle",{}).get("vault_service_capabilities",{})
    required_vault_caps={"CAP_SYS_ADMIN"}
    req(set(vault_caps.get("bounding_set",[]))==required_vault_caps and set(vault_caps.get("ambient",[]))==required_vault_caps and vault_caps.get("broader_capabilities")=="FORBIDDEN","SB-020A")
    mount_ns=p.get("lifecycle",{}).get("mount_namespace_contract",{})
    req(mount_ns.get("mount_unit")=="run-fa3-machine\\x2dstate.mount" and mount_ns.get("mount_unit_where")=="/run/fa3/machine-state" and mount_ns.get("mount_unit_type")=="ext4" and set(mount_ns.get("mount_unit_options",[]))=={"nodev","nosuid","noexec"} and mount_ns.get("mount_visibility")=="SYSTEM_MANAGER_MAIN_MOUNT_NAMESPACE" and mount_ns.get("credential_service_role")=="LUKS_MAPPER_ONLY" and mount_ns.get("credential_service_mount_ownership")=="FORBIDDEN" and mount_ns.get("credential_service_filesystem_namespace")=="MAY_BE_PRIVATE" and mount_ns.get("pid1_namespace_introspection")=="NOT_REQUIRED" and mount_ns.get("broker_mount_validation")=="HELPER_ASSERT_BROKER_OPEN_NO_DEVICE_ACCESS" and mount_ns.get("host_mount_source_validation")=="LIFECYCLE_ASSERT_OPEN_RESOLVES_EXPECTED_MAPPER","SB-020B")
    req("What=/dev/mapper/fa3-machine-state" in mount_unit and "Where=/run/fa3/machine-state" in mount_unit and "Type=ext4" in mount_unit and "Options=nodev,nosuid,noexec" in mount_unit and "Requires=fa3-secret-vault.service" in mount_unit and "PartOf=fa3-secrets.target" in mount_unit,"SB-020C")
    req("readlink /proc/1/ns/mnt" not in mount and "open_mapper" in mount and "close_mapper" in mount and "assert_open" in mount and "vault mount source mismatch" in mount and "refusing LUKS close while vault mount is active" in mount,"SB-020D")
    req("LoadCredentialEncrypted=fa3-machine-state-key:" in vault_unit and "CapabilityBoundingSet=CAP_SYS_ADMIN" in vault_unit and "AmbientCapabilities=CAP_SYS_ADMIN" in vault_unit and "CAP_CHOWN" not in vault_unit and "CAP_FOWNER" not in vault_unit and "ExecStart=/usr/local/libexec/fa3-secret-vault-mount open-mapper" in vault_unit and "ExecStop=/usr/local/libexec/fa3-secret-vault-mount close-mapper" in vault_unit,"SB-021")
    req("User=fa3-secret-broker" in broker_unit and "NoNewPrivileges=true" in broker_unit and "RestrictAddressFamilies=AF_UNIX" in broker_unit and "CapabilityBoundingSet=" in broker_unit and "Requires=run-fa3-machine\\x2dstate.mount" in broker_unit and "ExecStartPre=/usr/local/libexec/fa3-secret-vault-mount assert-broker-open" in broker_unit and "chgrp fa3-secret-clients /run/fa3-secret-broker" in broker_unit,"SB-022")
    req("Requires=fa3-secret-broker.service" in target and "PartOf=fa3-secrets.target" in broker_unit and "PartOf=fa3-secrets.target" in mount_unit and "PartOf=fa3-secrets.target" in vault_unit,"SB-023")
    lifecycle=(ROOT/"libexec/fa3-secrets-lifecycle.sh").read_text()
    installer=(ROOT/"bin/fa3-secret-broker-install").read_text()
    exit_contract=p.get("lifecycle",{}).get("fa3_exit_contract",{})
    start_requires={"SECRETS_TARGET_ACTIVE","MAPPER_SERVICE_ACTIVE","SYSTEMD_MOUNT_UNIT_ACTIVE","VAULT_MOUNT_VALIDATED","LUKS_MAPPING_OPEN","BROKER_SERVICE_ACTIVE","BROKER_SOCKET_PRESENT","BROKER_HEALTH_PASS"}
    req(set(p.get("lifecycle",{}).get("start_completion_requires",[]))==start_requires and p.get("lifecycle",{}).get("start_readiness_timeout")=="FAIL_CLOSED_ROLLBACK_TO_CLOSED","SB-023A0")
    req(exit_contract.get("command")=="/usr/local/sbin/fa3-secrets-lifecycle exit" and set(exit_contract.get("completion_requires",[]))=={"SECRETS_TARGET_INACTIVE","SECRET_DEPENDENT_PROVIDERS_STOPPED","SECRET_BROKER_INACTIVE","SYSTEMD_MOUNT_UNIT_INACTIVE","MAPPER_SERVICE_INACTIVE","VAULT_UNMOUNTED","LUKS_MAPPING_CLOSED"} and exit_contract.get("incomplete_shutdown")=="FAIL_CLOSED_NOT_EXITED","SB-023A")
    req("systemctl stop fa3-secrets.target" in lifecycle and "systemctl is-active --quiet fa3-secrets.target" in lifecycle and "mountpoint -q" in lifecycle and "/dev/mapper/$MAPPER" in lifecycle and "assert_closed" in lifecycle and "wait_broker_ready" in lifecycle and '[[ -S "$BROKER_SOCKET" ]]' in lifecycle and '"$BROKER_HEALTH_CLI" --socket "$BROKER_SOCKET" health' in lifecycle and "diagnose_runtime" in lifecycle and "force_host_cleanup" in lifecycle and 'systemctl stop "$MOUNT_UNIT"' in lifecycle and '"$VAULT_MOUNT_HELPER" close-mapper' in lifecycle and "/usr/local/sbin/fa3-secrets-lifecycle" in installer,"SB-023B")
    operations=p.get("operator_operations",{})
    req(operations.get("entrypoint")=="/usr/local/bin/fa3-secrets-admin" and set(operations.get("credential_store",[]))=={"put","rotate","revoke","metadata","list"} and set(operations.get("recovery",[]))=={"backup","restore","rekey"} and set(operations.get("policy",[]))=={"policy-check","policy-install","policy-remove","policy-show","policy-list"} and operations.get("bulk_secret_export")=="FORBIDDEN","SB-023C")
    recovery=p.get("recovery",{})
    req(recovery.get("backup_source_state")=="VAULT_CLOSED_REQUIRED" and recovery.get("backup_external_naming")=="GENERIC_NON_DISCLOSING" and recovery.get("restore_final_state")=="CLOSED" and recovery.get("failed_restore")=="ROLLBACK_PREVIOUS_ENCRYPTED_IMAGE_AND_REMAIN_CLOSED","SB-023D")
    admin=(ROOT/"bin/fa3-secrets-admin").read_text()
    policyctl=(ROOT/"bin/fa3-secret-policyctl").read_text()
    recovery_tool=(ROOT/"bin/fa3-secret-vault-recovery").read_text()
    rekey_tool=(ROOT/"bin/fa3-secret-vault-rekey").read_text()
    req("policy-check" in admin and "policy-install" in admin and "rotate" in admin and "revoke" in admin and "backup" in admin and "restore" in admin and "rekey" in admin and "assert-closed" in admin,"SB-023E")
    req("exportable must be false" in policyctl and "machine/service secret requires exactly one dedicated non-root consumer user" in policyctl and "machine/service consumer must be a member of fa3-secret-clients" in policyctl and '"check"' in policyctl,"SB-023F")
    req('"vault_closed_during_backup":True' in recovery_tool and '"final_vault_state":"CLOSED"' in recovery_tool and "assert_closed" in recovery_tool and "broker_health_result" in recovery_tool,"SB-023G")
    req("/usr/local/bin/fa3-secrets-admin" in installer and "/usr/local/sbin/fa3-secret-vault-recovery" in installer and "/usr/local/sbin/fa3-secret-vault-rekey" in installer and "/usr/local/sbin/fa3-secret-policyctl" in installer and "run-fa3-machine\\\\x2dstate.mount" in installer,"SB-023H")
    req("--with-key=host" in rekey_tool and "luksAddKey" in rekey_tool and "luksRemoveKey" in rekey_tool and "open --test-passphrase" in rekey_tool and "final state: CLOSED" in rekey_tool and "FA3_REKEY_NEW_KEY_FILE" in rekey_tool,"SB-023J")
    bridge_installer=(ROOT/"bin/fa3-install-secret-broker-current-host-bridge.sh").read_text()
    bridge_client=(ROOT/"libexec/fa3-secret-broker-current-host-bridge.sh").read_text()
    bridge_root=(ROOT/"libexec/fa3-secret-broker-current-host-root.sh").read_text()
    bridge_workflow=(ROOT/".github/workflows/fa3-secret-broker-current-host.yml").read_text()
    bootstrap=(ROOT/"bin/fa3-current-host-runner-bootstrap.sh").read_text()
    req('NOPASSWD: %s ""' in bridge_installer and "GENERAL_PASSWORDLESS_SUDO: NO" in bridge_installer and "git -C" in bridge_installer and "archive --format=tar" in bridge_installer,"SB-023K")
    req("privileged helper accepts no arguments" in bridge_root and 'PACKAGE_ROOT="/usr/local/lib/fa3/current-host-secret-broker"' in bridge_root and "FA3_CURRENT_HOST_PRIVILEGED_BRIDGE_SOURCE_COMMIT" in bridge_root,"SB-023L")
    req('sudo -n "$HELPER"' in bridge_client and "privileged bridge source drift" in bridge_client and "git -C" in bridge_client,"SB-023M")
    req("/usr/local/bin/fa3-secret-broker-current-host-bridge doctor" in bridge_workflow and "/usr/local/bin/fa3-secret-broker-current-host-bridge run" in bridge_workflow and "sudo FA3_REPO_ROOT" not in bridge_workflow,"SB-023N")
    req("fa3-install-secret-broker-current-host-bridge.sh" in bootstrap and "fa3-secret-broker-current-host-bridge" in bootstrap,"SB-023O")
    current_host=(ROOT/"bin/fa3-secret-broker-current-host.sh").read_text()
    privilege=p.get("current_host_privilege_boundary",{})
    req(privilege.get("broker_admin_e2e_identity")=="DEDICATED_EPHEMERAL_NON_ROOT" and set(privilege.get("broker_admin_required_groups",[]))=={"fa3-secret-admin","fa3-secret-clients"} and privilege.get("root_peer_admin_assumption_for_e2e")=="FORBIDDEN" and privilege.get("broker_admin_e2e_cleanup")=="REMOVE_BEFORE_RECEIPT","SB-023P")
    req('ADMIN_USER="fa3-sb-admin-probe"' in current_host and '--groups fa3-secret-admin,fa3-secret-clients "$ADMIN_USER"' in current_host and 'runuser -u "$ADMIN_USER"' in current_host and '"non_root_admin_authorization_pass":True' in current_host and '"ephemeral_admin_probe_removed_pass":True' in current_host and 'userdel "$ADMIN_USER"' in current_host,"SB-023Q")
    req("journalctl --no-pager -n 160 -u fa3-secret-vault.service -u \"$MOUNT_UNIT\" -u fa3-secret-broker.service" in lifecycle and "broker readiness/health timeout" in lifecycle and '/usr/local/sbin/fa3-secrets-lifecycle start' in current_host and "broker health failed after lifecycle readiness PASS" in current_host and "fa3-secret-broker-current-host.lock" in current_host and "fa3-machine-state-e2e-*" in current_host and '"host_mount_namespace_visibility_pass":True' in current_host,"SB-023R")
    example_projection=(ROOT/"deployment/secrets/fa3-example-secret-projection.service").read_text()
    req("PartOf=fa3-secrets.target" in example_projection and "fa3-secret-clients" in example_projection,"SB-023I")
    sv=load("canonical/profiles/FA3-SESSION-VAULT-001.json")
    req(sv.get("machine_secret_boundary",{}).get("profile")=="FA3-SECRET-BROKER-001" and sv["machine_secret_boundary"].get("raw_machine_application_secret_storage")=="FORBIDDEN","SB-024")
    return {"schema":"fa3.secret-broker-gate-report.v1","gate_id":"FA3-GATE-SECRET-BROKER-001","result":"PASS" if not findings else "FAIL","findings":findings,"production_runtime_promoted":False,"global_promotion_claim":False,"capability_count":143}
def main()->int:
    out=check()
    q=ROOT/"reports/secret-broker-gate-report.json";q.parent.mkdir(parents=True,exist_ok=True);q.write_text(json.dumps(out,indent=2)+"\n")
    print(json.dumps(out,indent=2));return 0 if out["result"]=="PASS" else 2
if __name__=="__main__":raise SystemExit(main())
